//! Actual backend binary with cleared environment and disposable infrastructure.
use crate::state::AppState;
use serde_json::Value;
use std::{path::Path, process::Stdio, time::Duration};
use tokio::process::{Child, Command};

pub(super) struct Service {
    _child: Child,
    pub(super) base: String,
}
impl Service {
    pub(super) async fn start(state: &AppState, out: &Path, binary: &str) -> Self {
        // The HTTP fixture originally seeds explicit IDs only. Startup inserts
        // role/permission rows by name/key, so its disposable tables need defaults.
        for statement in [
            "ALTER TABLE public.auth_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY",
            "ALTER TABLE public.auth_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY",
            "SELECT setval(pg_get_serial_sequence('public.auth_roles','id'), (SELECT MAX(id) FROM public.auth_roles))",
            "SELECT setval(pg_get_serial_sequence('public.auth_permissions','id'), (SELECT MAX(id) FROM public.auth_permissions))",
        ] {
            sqlx::query(statement).execute(&state.pool).await.unwrap();
        }
        let cwd = out.join("isolated-startup/cwd");
        std::fs::create_dir_all(&cwd).unwrap();
        let cwd = cwd.canonicalize().unwrap();
        for dir in [cwd.as_path(), cwd.parent().unwrap()] {
            for name in [".env", ".env.local", ".env.content-assets.local"] {
                assert!(!dir.join(name).exists(), "must not load host env files");
            }
        }
        let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
        let port = listener.local_addr().unwrap().port();
        drop(listener);
        let log = std::fs::File::create(out.join("service-startup.log")).unwrap();
        let s = &state.settings;
        let mut child = Command::new(binary)
            .current_dir(cwd)
            .env_clear()
            .env("DATABASE_URL", &s.database_url)
            .env("DRAGONFLY_URL", &s.dragonfly_url)
            .env("SECRET_KEY", &s.secret_key)
            .env("RUST_API_HOST", "127.0.0.1")
            .env("RUST_API_PORT", port.to_string())
            .env("CONTENT_PRODUCTION_ENABLED", "true")
            .env("CONTENT_PRODUCTION_RUNS_ENABLED", "true")
            .env("CONTENT_PRODUCTION_PLANNING_ENABLED", "true")
            .env("AIOS_CAPTION_PREFLIGHT_ENABLED", "true")
            .env("AIOS_VISUAL_REVIEW_MODEL", "fixture")
            .env("AIOS_CAPTION_PREFLIGHT_MAX_CALLS", "3")
            .env("TOS_BUCKET", &s.tos_bucket)
            .env(
                "CONTENT_ASSET_DELIVERY_PROVIDER",
                &s.content_asset_delivery_provider,
            )
            .env("CONTENT_ASSET_CDN_BASE_URL", &s.content_asset_cdn_base_url)
            .env("LLM_DEFAULT_PROVIDER", "deepseek")
            .env("LLM_DEFAULT_MODEL", &s.llm_default_model)
            .env("DEEPSEEK_BASE_URL", &s.deepseek_base_url)
            .env("DEEPSEEK_API_KEY", &s.deepseek_api_key)
            .env("DEEPSEEK_MODEL", &s.deepseek_model)
            .env("RUST_LOG", "warn")
            .stdout(Stdio::from(log.try_clone().unwrap()))
            .stderr(Stdio::from(log))
            .kill_on_drop(true)
            .spawn()
            .unwrap();
        let base = format!("http://127.0.0.1:{port}");
        let client = reqwest::Client::new();
        tokio::time::timeout(Duration::from_secs(30), async {
            loop {
                assert!(
                    child.try_wait().unwrap().is_none(),
                    "service exited; inspect service-startup.log"
                );
                if let Ok(response) = client.get(format!("{base}/health")).send().await {
                    if response.status().is_success() {
                        break;
                    }
                }
                tokio::time::sleep(Duration::from_millis(200)).await;
            }
        })
        .await
        .expect("startup did not become healthy");
        let service = Self {
            _child: child,
            base,
        };
        service.check().await;
        service
    }
    pub(super) async fn check(&self) {
        let value: Value = reqwest::get(format!("{}/health", self.base))
            .await
            .unwrap()
            .json()
            .await
            .unwrap();
        assert_eq!(value["database"], "ok");
        assert_eq!(value["dragonfly"], "ok");
    }
    pub(super) async fn post(&self, path: &str, body: &Value) -> Value {
        let token =
            crate::marketing::content_assets::handlers::qianchuan_http_route_tests::access_token();
        let response = reqwest::Client::new()
            .post(format!(
                "{}/v1/marketing/content-assets/production/{path}",
                self.base
            ))
            .bearer_auth(token)
            .json(body)
            .send()
            .await
            .unwrap();
        let status = response.status();
        let value: Value = response.json().await.unwrap();
        assert!(status.is_success(), "{status}: {value}");
        value
    }
    pub(super) async fn read_result(&self, run: uuid::Uuid) -> Value {
        let url = format!(
            "{}/v1/marketing/content-assets/production/runs/{run}/result",
            self.base
        );
        let client = reqwest::Client::new();
        assert_eq!(client.get(&url).send().await.unwrap().status(), 401);
        let token =
            crate::marketing::content_assets::handlers::qianchuan_http_route_tests::access_token();
        let response = client.get(url).bearer_auth(token).send().await.unwrap();
        assert_eq!(response.status(), 200);
        response.json().await.unwrap()
    }
}
