#[derive(Debug, Clone)]
pub(crate) struct DashboardGoodsCardTrafficMetricRow {
    pub(super) source_key: String,
    pub(super) parent_source_key: String,
    pub(super) source_level: i32,
    pub(super) source_name: String,
    pub(super) parent_source_name: String,
    pub(super) curr_card_exposure_user_count: f64,
    pub(super) prev_card_exposure_user_count: f64,
    pub(super) curr_card_click_user_count: f64,
    pub(super) prev_card_click_user_count: f64,
    pub(super) curr_card_buyer_count: f64,
    pub(super) prev_card_buyer_count: f64,
    pub(super) curr_card_cart_user_count: f64,
    pub(super) prev_card_cart_user_count: f64,
    pub(super) curr_card_favorite_user_count: f64,
    pub(super) prev_card_favorite_user_count: f64,
    pub(super) curr_card_bounce_user_count: f64,
    pub(super) prev_card_bounce_user_count: f64,
    pub(super) curr_card_user_pay_amount: f64,
    pub(super) prev_card_user_pay_amount: f64,
    pub(super) curr_card_order_count: f64,
    pub(super) prev_card_order_count: f64,
    pub(super) curr_card_click_rate_user: f64,
    pub(super) prev_card_click_rate_user: f64,
    pub(super) curr_card_click_to_pay_rate_user: f64,
    pub(super) prev_card_click_to_pay_rate_user: f64,
    pub(super) curr_card_exposure_to_pay_rate_user: f64,
    pub(super) prev_card_exposure_to_pay_rate_user: f64,
}
