COMMENT ON COLUMN ads.douyin_shortvideo_detail.stat_date IS '短视频成交或千川素材指标日期。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.shop_name IS '抖音店铺名称。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.shop_id IS '抖音店铺 ID。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.account_type IS '成交侧账号类型，空值统一归为未归类。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.account_types IS '同一视频日聚合到的账号类型集合。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.video_title IS '短视频或图文短视频标题。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.video_id IS '短视频或图文短视频 ID。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.is_promoted IS '成交侧是否投放标识。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.play_url IS '短视频播放链接。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.publish_time IS '短视频发布时间。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.author_nickname IS '作者或达人昵称。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.author_douyin_id IS '作者或达人抖音号。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.product_id IS '短视频关联商品 ID。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.trade_source_ids IS '聚合到该行的成交侧 ODS 源记录 ID 集合。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.video_view_count IS '成交侧视频观看次数。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.user_pay_amount IS '成交侧用户支付金额。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.refund_amount IS '成交侧退款金额。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.live_room_pay_amount IS '短视频引导直播间用户支付金额。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.search_after_view_pay_amount IS '短视频看后搜用户支付金额。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.shop_page_pay_amount IS '短视频引导店铺页用户支付金额。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.trade_created_at IS '成交侧源记录最早创建时间。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.trade_updated_at IS '成交侧源记录最新更新时间。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.asset_ids IS '匹配到的营销内容资产 ID 集合。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.platform_video_ids IS '匹配到的平台视频映射 ID 集合。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.ad_material_ids IS '匹配到的广告素材映射 ID 集合。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_material_ids IS '聚合到该行的千川素材 ID 集合。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_material_count IS '聚合到该行的千川素材数量。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_material_video_names IS '聚合到该行的千川素材视频名称集合。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_material_created_at_min IS '聚合千川素材的最早创建时间。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_material_created_at_max IS '聚合千川素材的最晚创建时间。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_impression_count IS '千川整体曝光次数。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_click_count IS '千川整体点击次数。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_click_rate IS '千川整体点击率。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_conversion_rate IS '千川整体转化率。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_cost IS '千川整体广告消耗金额。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_order_count IS '千川整体成交订单数。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_gmv IS '千川整体成交 GMV。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_pay_roi IS '千川整体支付 ROI。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_order_cost IS '千川整体成交订单成本。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_user_pay_amount IS '千川归因用户支付金额。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_cpm IS '千川整体千次曝光成本（CPM）。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_overall_cpc IS '千川整体点击成本（CPC）。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_smart_coupon_amount IS '千川智能优惠券金额。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_platform_subsidy_amount IS '千川平台补贴金额。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_net_gmv_roi IS '千川净 GMV 投产比：净 GMV / 广告消耗。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_net_gmv IS '千川净 GMV。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_net_order_count IS '千川净成交订单数。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_net_order_cost IS '千川净成交订单成本。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_net_gmv_settlement_rate IS '千川净 GMV 结算率：净 GMV / 整体 GMV。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_refund_rate_1h IS '千川 1 小时退款率，按整体 GMV 加权聚合。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_source_file_names IS '聚合到该行的千川来源文件名集合。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_source_ids IS '聚合到该行的千川 ODS 源记录 ID 集合。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_ingest_time IS '千川源数据导入时间。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.trade_source_updated_at IS '成交侧源数据更新时间。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.qianchuan_source_updated_at IS '千川侧源数据更新时间。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.created_at IS '短视频宽表记录创建时间。';
COMMENT ON COLUMN ads.douyin_shortvideo_detail.updated_at IS '短视频宽表记录最后更新时间。';
