COMMENT ON COLUMN ads.douyin_trade_sale_card.id IS '来源 ODS 商品卡主表记录 ID。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.shop_name IS '抖音店铺名称。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.shop_id IS '抖音店铺 ID。';
COMMENT ON COLUMN ads.douyin_trade_sale_card."date" IS '商品卡指标日期。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.product_title IS '商品标题。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.product_id IS '商品 ID。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.product_url IS '商品链接。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_exposure_user_count IS '商品卡曝光人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_click_user_count IS '商品卡点击人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_click_rate_user IS '按人数计算的商品卡点击率：点击人数 / 曝光人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_click_count IS '商品卡点击次数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_avg_click_per_user IS '人均商品卡点击次数：点击次数 / 点击人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.new_customer_click_count IS '新客商品卡点击次数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.old_customer_click_count IS '老客商品卡点击次数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.new_customer_click_rate IS '新客点击占比：新客点击次数 / 商品卡点击次数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.old_customer_click_rate IS '老客点击占比：老客点击次数 / 商品卡点击次数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_user_pay_amount IS '商品卡引导用户支付金额。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_buyer_count IS '商品卡引导支付买家数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_avg_order_value IS '商品卡客单价：用户支付金额 / 支付买家数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_click_to_pay_rate_user IS '按人数计算的商品卡点击支付转化率：支付买家数 / 点击人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.first_buy_user_count IS '商品卡首购用户数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.rebuy_user_count IS '商品卡复购用户数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.first_buy_new_rate IS '首购用户占比：首购用户数 / 支付买家数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.rebuy_old_rate IS '复购用户占比：复购用户数 / 支付买家数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_exposure_count IS '商品卡曝光次数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_exposure_to_pay_rate_user IS '按人数计算的商品卡曝光支付转化率：支付买家数 / 曝光人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_exposure_to_pay_rate_count IS '按次数计算的商品卡曝光支付转化率：订单数 / 曝光次数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_gpm IS '商品卡千次曝光成交金额：用户支付金额 / 曝光次数 * 1000。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_click_rate_count IS '按次数计算的商品卡点击率：点击次数 / 曝光次数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_click_to_pay_rate_count IS '按次数计算的商品卡点击支付转化率：订单数 / 点击次数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_cart_user_count IS '商品卡加购用户数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_favorite_user_count IS '商品卡收藏用户数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.card_order_count IS '商品卡引导订单数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.platform_support_exposure_count IS '平台补贴或扶持曝光次数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.created_at IS 'ADS 商品卡主表记录创建时间。';
COMMENT ON COLUMN ads.douyin_trade_sale_card.updated_at IS 'ADS 商品卡主表记录最后更新时间。';

COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.id IS '来源 ODS 商品卡流量来源明细记录 ID。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.shop_name IS '抖音店铺名称。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.shop_id IS '抖音店铺 ID。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.stat_date IS '商品卡流量来源明细指标日期。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.product_title IS '商品标题。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.product_id IS '商品 ID。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.product_url IS '商品链接。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.source_level1 IS '一级流量来源标识。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_exposure_user_count IS '该流量来源下的商品卡曝光人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_click_user_count IS '该流量来源下的商品卡点击人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_buyer_count IS '该流量来源下的商品卡支付买家数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_cart_user_count IS '该流量来源下的商品卡加购用户数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_favorite_user_count IS '该流量来源下的商品卡收藏用户数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_bounce_user_count IS '该流量来源下的商品卡跳出用户数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_exposure_to_pay_rate_user IS '按人数计算的曝光支付转化率：支付买家数 / 曝光人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_click_rate_user IS '按人数计算的商品卡点击率：点击人数 / 曝光人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_click_to_pay_rate_user IS '按人数计算的点击支付转化率：支付买家数 / 点击人数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_user_pay_amount IS '该流量来源下的商品卡引导用户支付金额。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.card_order_count IS '该流量来源下的商品卡引导订单数。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.created_at IS 'ADS 商品卡流量来源明细记录创建时间。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail.updated_at IS 'ADS 商品卡流量来源明细记录最后更新时间。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail."售卖类型" IS '业务侧售卖类型。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail."投广时段" IS '业务侧投广时段。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail."一级渠道" IS '业务侧一级渠道。';
COMMENT ON COLUMN ads.douyin_trade_sale_card_detail."二级渠道" IS '业务侧二级渠道。';
