COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.id IS '当前生效校准参数自增主键。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.platform IS '适用平台标识。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.eval_age_days IS '预测龄期档位，表示观察日期距业务日期的天数。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.effective_from IS '校准参数生效起始日期。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.effective_to IS '校准参数生效结束日期，空值表示当前仍生效。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.source_as_of_date IS '生成该生效参数的周度校准观察日期。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.source_weekly_id IS '来源周度校准审计记录 ID。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.source_model_version IS '来源预测模型版本。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.previous_factor IS '激活前同平台同龄期的上一生效预测倍率。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.sample_count IS '来源周度校准样本数。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.wape_before IS '应用候选倍率前的加权绝对百分比误差（WAPE）。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.wape_after IS '应用候选倍率后的加权绝对百分比误差（WAPE）。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.bias_before IS '应用候选倍率前的预测偏差率。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.bias_after IS '应用候选倍率后的预测偏差率。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.wape_delta IS '应用后 WAPE 与应用前 WAPE 的差值，负数表示改善。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.bias_abs_delta IS '应用后绝对偏差率与应用前绝对偏差率的差值，负数表示改善。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.activation_reason IS '激活、替换或退役该校准参数的原因说明。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.created_at IS '校准参数记录创建时间。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_active_calibration.updated_at IS '校准参数记录最后更新时间。';

COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.id IS '周度校准审计记录自增主键。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.as_of_date IS '周度校准计算观察日期。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.platform IS '适用平台标识。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.eval_age_days IS '预测龄期档位，表示观察日期距业务日期的天数。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.eval_window_days IS '用于周度校准回测的窗口天数。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.source_model_version IS '参与周度校准的预测模型版本。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.sample_count IS '周度校准回测样本数。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.actual_total IS '回测窗口内成熟观测退款金额合计。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.predicted_total IS '回测窗口内对应预测退款金额合计。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.zero_miss_count IS '预测为 0 但成熟观测退款大于 0 的样本数。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.wape_before IS '候选调整前的加权绝对百分比误差（WAPE）。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.bias_before IS '候选调整前的预测偏差率。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.wape_after IS '候选调整后的加权绝对百分比误差（WAPE）。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.bias_after IS '候选调整后的预测偏差率。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.quality_status IS '周度校准质量状态：pass、alert 或 insufficient。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.recommendation_status IS '周度校准建议状态。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.recommendation_reason IS '生成该周度校准建议的原因说明。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.created_at IS '周度校准审计记录创建时间。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_calibration_weekly.updated_at IS '周度校准审计记录最后更新时间。';

COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_daily."date" IS '预测对应的业务日期。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_daily.platform IS '适用平台标识。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_daily.as_of_date IS '预测生成或观测截止日期。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_daily.model_version IS '生成预测值的模型版本。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_daily.created_at IS '退款 nowcast 日快照创建时间。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_daily.updated_at IS '退款 nowcast 日快照最后更新时间。';

COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_event_calendar.id IS '活动日修正规则自增主键。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_event_calendar.start_date IS '活动日修正规则开始日期。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_event_calendar.end_date IS '活动日修正规则结束日期。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_event_calendar.is_active IS '是否启用该活动日修正规则。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_event_calendar.note IS '活动日修正规则备注。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_event_calendar.created_at IS '活动日修正规则创建时间。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_event_calendar.updated_at IS '活动日修正规则最后更新时间。';

COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_quality_daily.as_of_date IS '质量评估观察日期。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_quality_daily.platform IS '适用平台标识。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_quality_daily.threshold_wape IS '质量告警使用的 WAPE 阈值。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_quality_daily.sample_count IS '质量评估样本数。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_quality_daily.actual_total IS '评估窗口内成熟观测退款金额合计。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_quality_daily.predicted_total IS '评估窗口内预测退款金额合计。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_quality_daily.absolute_error_total IS '评估窗口内绝对误差金额合计。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_quality_daily.created_at IS '质量评估快照创建时间。';
COMMENT ON COLUMN ads.all_trade_overview_refund_nowcast_quality_daily.updated_at IS '质量评估快照最后更新时间。';
