COMMENT ON COLUMN ads.creator_library_bd_identity.id IS 'BD 身份映射自增主键。';
COMMENT ON COLUMN ads.creator_library_bd_identity.user_id IS 'DataHub 用户 ID，来源于系统用户身份。';
COMMENT ON COLUMN ads.creator_library_bd_identity.username IS 'DataHub 登录用户名。';
COMMENT ON COLUMN ads.creator_library_bd_identity.display_name IS '用户展示名称。';
COMMENT ON COLUMN ads.creator_library_bd_identity.owner_alias IS '业务侧 owner 别名，用于达人/内容归属匹配。';
COMMENT ON COLUMN ads.creator_library_bd_identity.owner_alias_norm IS '标准化 owner 别名，用于大小写和空白归一后的匹配。';
COMMENT ON COLUMN ads.creator_library_bd_identity.is_primary IS '是否为该用户的主要 owner 映射。';
COMMENT ON COLUMN ads.creator_library_bd_identity.is_active IS '映射是否启用。';
COMMENT ON COLUMN ads.creator_library_bd_identity.created_at IS '映射创建时间。';
COMMENT ON COLUMN ads.creator_library_bd_identity.updated_at IS '映射最后更新时间。';

COMMENT ON COLUMN ads.influencer_library_follow_log.id IS '达人库跟进日志自增主键。';
COMMENT ON COLUMN ads.influencer_library_follow_log.influencer_library_id IS '关联的达人库主表 ID。';
COMMENT ON COLUMN ads.influencer_library_follow_log.follow_note IS '跟进备注正文。';
COMMENT ON COLUMN ads.influencer_library_follow_log.created_by IS '创建跟进记录的用户展示名或账号标识。';
COMMENT ON COLUMN ads.influencer_library_follow_log.updated_by IS '最后更新跟进记录的用户展示名或账号标识。';
COMMENT ON COLUMN ads.influencer_library_follow_log.created_by_user_id IS '创建跟进记录的系统用户 ID。';
COMMENT ON COLUMN ads.influencer_library_follow_log.updated_by_user_id IS '最后更新跟进记录的系统用户 ID。';
COMMENT ON COLUMN ads.influencer_library_follow_log.created_at IS '跟进记录创建时间。';
COMMENT ON COLUMN ads.influencer_library_follow_log.updated_at IS '跟进记录最后更新时间。';
COMMENT ON COLUMN ads.influencer_library_follow_log.is_deleted IS '是否软删除该跟进记录。';
COMMENT ON COLUMN ads.influencer_library_follow_log.deleted_by IS '软删除操作人的展示名或账号标识。';
COMMENT ON COLUMN ads.influencer_library_follow_log.deleted_by_user_id IS '软删除操作人的系统用户 ID。';
COMMENT ON COLUMN ads.influencer_library_follow_log.deleted_at IS '软删除时间。';

COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.stat_date IS '指标日期。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.source_system IS '来源系统标识。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.ad_platform IS '广告投放平台。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.account_id IS '广告账户 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.account_name IS '广告账户名称。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.advertiser_id IS '广告主 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.external_material_id IS '外部广告平台素材 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.external_video_id IS '外部广告平台视频 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.campaign_id IS '广告计划 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.campaign_name IS '广告计划名称。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.ad_group_id IS '广告组 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.ad_group_name IS '广告组名称。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.ad_id IS '广告创意或广告单元 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.ad_name IS '广告创意或广告单元名称。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.asset_id IS '匹配到的营销内容资产 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.platform_video_id IS '匹配到的平台视频映射 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.ad_material_id IS '匹配到的广告素材映射 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.match_status IS '素材与内容资产的匹配状态。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.impressions IS '曝光次数。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.clicks IS '点击次数。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.ctr IS '点击率。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.conversions IS '转化次数。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.cvr IS '转化率。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.cost IS '广告消耗金额。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.gmv IS '广告归因 GMV。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.roi IS '投放 ROI。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.live_room_entries IS '进入直播间次数。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.live_room_entry_rate IS '直播间进入率。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.transaction_cost IS '成交成本。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.likes IS '点赞数。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.comments IS '评论数。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.shares IS '分享数。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.follows IS '新增关注数。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.source_ingest_id IS '来源导入批次 ID。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.source_row_hash IS '来源行内容哈希，用于幂等和变更识别。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.raw_payload IS '来源原始行 JSON。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.created_at IS 'DWD 记录创建时间。';
COMMENT ON COLUMN dwd.marketing_content_ad_material_stats_di.updated_at IS 'DWD 记录最后更新时间。';

COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.stat_date IS '指标日期。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.source_system IS '来源系统标识。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.platform IS '内容发布平台。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.account_id IS '平台账号 ID。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.account_name IS '平台账号名称。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.external_video_id IS '外部平台视频 ID。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.external_item_id IS '外部平台内容 item ID。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.external_note_id IS '外部平台笔记 ID。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.external_url IS '外部平台内容 URL。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.asset_id IS '匹配到的营销内容资产 ID。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.platform_video_id IS '匹配到的平台视频映射 ID。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.match_status IS '平台内容与资产的匹配状态。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.impressions IS '曝光次数。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.plays IS '播放次数。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.reads IS '阅读次数。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.clicks IS '点击次数。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.likes IS '点赞数。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.comments IS '评论数。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.shares IS '分享数。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.collects IS '收藏数。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.follows IS '新增关注数。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.completion_rate IS '完播率。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.avg_watch_seconds IS '平均观看时长（秒）。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.source_ingest_id IS '来源导入批次 ID。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.source_row_hash IS '来源行内容哈希，用于幂等和变更识别。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.raw_payload IS '来源原始行 JSON。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.created_at IS 'DWD 记录创建时间。';
COMMENT ON COLUMN dwd.marketing_content_platform_video_stats_di.updated_at IS 'DWD 记录最后更新时间。';

COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.stat_date IS '汇总日期。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.asset_id IS '营销内容资产 ID。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.platform IS '平台。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.account_id IS '账号 ID。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.account_name IS '账号名称。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.product_name IS '关联产品名称。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.creator_name IS '内容创作者名称。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.material_count IS '关联广告素材数量。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.video_count IS '关联平台视频或笔记数量。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.impressions IS '曝光次数。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.plays IS '播放次数。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.clicks IS '点击次数。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.conversions IS '转化次数。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.cost IS '广告消耗金额。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.gmv IS '归因 GMV。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.roi IS '投资回报率（ROI）。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.ctr IS '点击率。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.cvr IS '转化率。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.likes IS '点赞数。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.comments IS '评论数。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.shares IS '分享数。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.collects IS '收藏数。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.follows IS '新增关注数。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.live_room_entries IS '进入直播间次数。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.live_room_entry_rate IS '直播间进入率。';
COMMENT ON COLUMN dws.marketing_content_asset_daily_summary.updated_at IS '汇总记录最后更新时间。';

COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.asset_id IS '营销内容资产 ID。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.first_stat_date IS '首次有指标的日期。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.last_stat_date IS '最近有指标的日期。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.platform_count IS '覆盖平台数量。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.account_count IS '覆盖账号数量。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.material_count IS '累计关联广告素材数量。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.video_count IS '累计关联平台视频或笔记数量。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.total_impressions IS '累计曝光次数。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.total_plays IS '累计播放次数。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.total_clicks IS '累计点击次数。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.total_conversions IS '累计转化次数。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.total_cost IS '累计广告消耗金额。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.total_gmv IS '累计归因 GMV。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.total_roi IS '累计 ROI。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.last_7d_cost IS '近 7 天广告消耗金额。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.last_7d_gmv IS '近 7 天归因 GMV。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.last_7d_roi IS '近 7 天 ROI。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.last_30d_cost IS '近 30 天广告消耗金额。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.last_30d_gmv IS '近 30 天归因 GMV。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.last_30d_roi IS '近 30 天 ROI。';
COMMENT ON COLUMN dws.marketing_content_asset_lifetime_summary.updated_at IS '生命周期汇总记录最后更新时间。';
