import type { DataOpsHubClientState } from './dataops-hub-client-state-contract';

const DATAOPS_HUB_OVERLAY_LAYER_PROP_KEYS = [
  'activeRetryGroupTraceId',
  'applyBatchHistoryReasonFilter',
  'applyRetryGroupTraceAsNotifyFilter',
  'availableAlertChannels',
  'batchExecutionHistory',
  'batchHistoryActionFilter',
  'batchHistoryAlertForm',
  'batchHistoryAlertModalCopy',
  'batchHistoryAlertModalOpen',
  'batchHistoryAlertSubmitting',
  'batchHistoryAlertTemplateText',
  'batchHistoryColumns',
  'batchHistoryFailureFilter',
  'batchHistoryFailureSummary',
  'batchHistoryFailureSummaryText',
  'batchHistoryKeyword',
  'batchHistoryMarkdownText',
  'batchHistoryMobileColumns',
  'batchHistoryModalOpen',
  'batchHistoryTimeRangeFilter',
  'batchResultColumns',
  'batchResultFailedPipelineIds',
  'batchResultFilter',
  'batchResultModalOpen',
  'batchResultMobileColumns',
  'batchResultRetryableFailedCount',
  'batchTriggerExecutionPreview',
  'batchTriggerForm',
  'batchTriggerModalPipelineIds',
  'batchTriggerModalPipelines',
  'batchTriggerModalSpecs',
  'clearRetryGroupTraceReasonHashFocus',
  'closeBatchHistoryAlertModal',
  'closeBatchHistoryModal',
  'closeBatchResultModal',
  'closeBatchTriggerModal',
  'closeCommandModal',
  'closeNotificationTraceSloScanModal',
  'closeRetryGroupTraceModal',
  'closeTriggerModal',
  'commandForm',
  'commandModalCommandPreview',
  'commandModalPipeline',
  'commandModalSpecs',
  'copyBatchFailedPipelineIds',
  'copyFilteredBatchHistoryFailedPipelineIds',
  'copyNotificationTraceSloScanMarkdown',
  'copyRetryGroupTraceLink',
  'copyRetryGroupTraceMarkdown',
  'copyTextToClipboard',
  'defaultAlertChannel',
  'exportFilteredBatchHistoryCsv',
  'exportRetryGroupTraceCsv',
  'filteredBatchHistoryFailedPipelineIds',
  'filteredBatchHistoryItems',
  'filteredBatchHistoryRetryableFailedPipelineIds',
  'filteredBatchHistoryRetryableGroups',
  'filteredBatchHistoryRetryGroups',
  'filteredBatchResultItems',
  'filteredRetryGroupTraceEvents',
  'focusRetryGroupTraceByReasonHash',
  'globalActionBusy',
  'handleBatchTriggerWithParameters',
  'handleTriggerWithParameters',
  'hasOperatePermission',
  'isBatchTriggerModalSubmitting',
  'isCompactViewport',
  'isTriggerModalSubmitting',
  'lastBatchExecutionSummary',
  'lastBatchFailureContext',
  'normalizedRetryGroupTraceReasonHashFocus',
  'notificationBatchRetrySubmitting',
  'notificationTraceSloScanColumns',
  'notificationTraceSloScanConcurrency',
  'notificationTraceSloScanDisplayedItems',
  'notificationTraceSloScanDryRun',
  'notificationTraceSloScanLookbackHours',
  'notificationTraceSloScanMarkdownText',
  'notificationTraceSloScanMaxGroups',
  'notificationTraceSloScanMobileColumns',
  'notificationTraceSloScanModalOpen',
  'notificationTraceSloScanQuickFilter',
  'notificationTraceSloScanRankedItems',
  'notificationTraceSloScanResult',
  'notificationTraceSloScanRiskSummary',
  'notificationTraceSloScanRunning',
  'openBatchHistoryAlertModal',
  'openNotifyTraceSloScanAlertModal',
  'resetBatchHistoryFilters',
  'retryableFailedCount',
  'retryCurrentTraceFailedNotifications',
  'retryCurrentTraceRetryableNotifications',
  'retryFilteredBatchHistoryByCurrentGroups',
  'retryGroupTraceColumns',
  'retryGroupTraceErrorMessage',
  'retryGroupTraceEvents',
  'retryGroupTraceFailedEvents',
  'retryGroupTraceFilter',
  'retryGroupTraceIsFetching',
  'retryGroupTraceMarkdownText',
  'retryGroupTraceModalOpen',
  'retryGroupTraceReasonHashFocusLabel',
  'retryGroupTraceReasonHashRecovery',
  'retryGroupTraceReasonHashRecoverySummary',
  'retryGroupTraceRetryableFailedEvents',
  'retryGroupTraceSloDescription',
  'retryGroupTraceSloStatus',
  'retryGroupTraceSource',
  'retryGroupTraceSummary',
  'retryLastFailedBatch',
  'retryLastRetryableFailedBatch',
  'runNotificationTraceSloScan',
  'runtimeDetailDrawerOpen',
  'runtimeStoreDerivedState',
  'runtimeWarnings',
  'setBatchHistoryActionFilter',
  'setBatchHistoryFailureFilter',
  'setBatchHistoryKeyword',
  'setBatchHistoryTimeRangeFilter',
  'setBatchResultFilter',
  'setNotificationTraceSloScanConcurrency',
  'setNotificationTraceSloScanDryRun',
  'setNotificationTraceSloScanLookbackHours',
  'setNotificationTraceSloScanMaxGroups',
  'setNotificationTraceSloScanQuickFilter',
  'setRetryGroupTraceFilter',
  'setRuntimeDetailDrawerOpen',
  'submitBatchHistoryAlertModal',
  'triggerForm',
  'triggerModalPipeline',
  'triggerModalSpecs',
] as const satisfies readonly (keyof DataOpsHubClientState)[];

export type DataOpsHubOverlayLayerProps = Pick<
  DataOpsHubClientState,
  (typeof DATAOPS_HUB_OVERLAY_LAYER_PROP_KEYS)[number]
>;

export function pickDataOpsHubOverlayLayerProps(
  state: DataOpsHubClientState,
): DataOpsHubOverlayLayerProps {
  return Object.fromEntries(
    DATAOPS_HUB_OVERLAY_LAYER_PROP_KEYS.map((key) => [key, state[key]]),
  ) as DataOpsHubOverlayLayerProps;
}
