import type { useDataOpsHubFoundationState } from './dataops-hub-foundation-state';
import type { useDataOpsNotificationWorkspaceState } from './dataops-notification-workspace-state';

type DataOpsHubFoundationState = ReturnType<typeof useDataOpsHubFoundationState>;
type DataOpsNotificationWorkspaceParams = Parameters<
  typeof useDataOpsNotificationWorkspaceState
>[0];

export function buildDataOpsNotificationWorkspaceParams({
  availableAlertChannelIdSet,
  availableAlertChannels,
  channelFilter,
  copyTextToClipboard,
  defaultAlertChannel,
  exportDataOpsCsv,
  getCurrentNotifyShareFilters,
  hasOperatePermission,
  isCompactViewport,
  keywordInput,
  message,
  modal,
  normalizedKeyword,
  normalizedNotifyReasonHashFilter,
  normalizedNotifyRetryGroupIdFilter,
  notificationChannelMap,
  notificationEventTypeFilter,
  notificationEvents,
  notificationStatusFilter,
  notifyFailureChannelFocus,
  openBatchHistoryAlertDraftModal,
  runtimeQuery,
  selectedNotifyFailureReason,
  setActiveTab,
  setChannelFilter,
  setNotificationEventTypeFilter,
  setNotificationStatusFilter,
  setNotifyFailureChannelFocus,
  setNotifyReasonHashFilter,
  setNotifyRetryGroupIdFilter,
  setSelectedNotifyFailureReason,
}: DataOpsHubFoundationState): DataOpsNotificationWorkspaceParams {
  return {
    notificationFilter: {
      availableAlertChannelIds: availableAlertChannelIdSet,
      channelFilter,
      copyText: copyTextToClipboard,
      exportCsv: exportDataOpsCsv,
      keywordInput,
      message,
      normalizedKeyword,
      normalizedNotifyReasonHashFilter,
      normalizedNotifyRetryGroupIdFilter,
      notificationChannelMap,
      notificationEventTypeFilter,
      notificationEvents,
      notificationStatusFilter,
      notifyFailureChannelFocus,
      selectedNotifyFailureReason,
      setChannelFilter,
      setNotificationEventTypeFilter,
      setNotificationStatusFilter,
      setNotifyFailureChannelFocus,
      setNotifyReasonHashFilter,
      setNotifyRetryGroupIdFilter,
      setSelectedNotifyFailureReason,
    },
    notificationRetry: {
      availableAlertChannelIds: availableAlertChannelIdSet,
      hasOperatePermission,
      message,
      modal,
      notificationChannelMap,
      refetchRuntime: runtimeQuery.refetch,
      selectedNotifyFailureReason,
    },
    notificationTraceSloScan: {
      availableAlertChannels,
      copyText: copyTextToClipboard,
      defaultAlertChannel,
      hasOperatePermission,
      message,
      openAlertDraft: openBatchHistoryAlertDraftModal,
      refetchRuntime: runtimeQuery.refetch,
    },
    retryGroupTrace: {
      availableAlertChannelIds: availableAlertChannelIdSet,
      copyText: copyTextToClipboard,
      exportCsv: exportDataOpsCsv,
      getCurrentNotifyShareFilters,
      isCompactViewport,
      message,
      notificationChannelMap,
      notificationEvents,
      setActiveTab,
      setNotifyRetryGroupIdFilter,
    },
  };
}
