'use client';
import { DataOpsBatchModals } from './dataops-batch-modals';
import { DataOpsNotificationTraceModals } from './dataops-notification-trace-modals';
import { DataOpsRuntimeDrawer } from './dataops-runtime-drawer';
import { DataOpsTriggerCommandModals } from './dataops-trigger-command-modals';
import type { DataOpsHubOverlayLayerProps } from './dataops-hub-view-contracts';

export function DataOpsHubOverlayLayer(props: DataOpsHubOverlayLayerProps) {
  const {
    activeRetryGroupTraceId,
    applyBatchHistoryReasonFilter,
    applyRetryGroupTraceAsNotifyFilter,
    availableAlertChannels,
    batchExecutionHistory,
    batchHistoryActionFilter,
    batchHistoryAlertForm,
    batchHistoryAlertModalCopy,
    batchHistoryAlertModalOpen,
    batchHistoryAlertSubmitting,
    batchHistoryAlertTemplateText,
    batchHistoryColumns,
    batchHistoryFailureFilter,
    batchHistoryFailureSummary,
    batchHistoryFailureSummaryText,
    batchHistoryKeyword,
    batchHistoryMarkdownText,
    batchHistoryMobileColumns,
    batchHistoryModalOpen,
    batchHistoryTimeRangeFilter,
    batchResultColumns,
    batchResultFailedPipelineIds,
    batchResultFilter,
    batchResultModalOpen,
    batchResultMobileColumns,
    batchResultRetryableFailedCount,
    batchTriggerExecutionPreview,
    batchTriggerForm,
    batchTriggerModalPipelineIds,
    batchTriggerModalPipelines,
    batchTriggerModalSpecs,
    clearRetryGroupTraceReasonHashFocus,
    closeBatchHistoryAlertModal,
    closeBatchHistoryModal,
    closeBatchResultModal,
    closeBatchTriggerModal,
    closeCommandModal,
    closeNotificationTraceSloScanModal,
    closeRetryGroupTraceModal,
    closeTriggerModal,
    commandForm,
    commandModalCommandPreview,
    commandModalPipeline,
    commandModalSpecs,
    copyBatchFailedPipelineIds,
    copyFilteredBatchHistoryFailedPipelineIds,
    copyNotificationTraceSloScanMarkdown,
    copyRetryGroupTraceLink,
    copyRetryGroupTraceMarkdown,
    copyTextToClipboard,
    defaultAlertChannel,
    exportFilteredBatchHistoryCsv,
    exportRetryGroupTraceCsv,
    filteredBatchHistoryFailedPipelineIds,
    filteredBatchHistoryItems,
    filteredBatchHistoryRetryableFailedPipelineIds,
    filteredBatchHistoryRetryableGroups,
    filteredBatchHistoryRetryGroups,
    filteredBatchResultItems,
    filteredRetryGroupTraceEvents,
    focusRetryGroupTraceByReasonHash,
    globalActionBusy,
    handleBatchTriggerWithParameters,
    handleTriggerWithParameters,
    hasOperatePermission,
    isBatchTriggerModalSubmitting,
    isCompactViewport,
    isTriggerModalSubmitting,
    lastBatchExecutionSummary,
    lastBatchFailureContext,
    normalizedRetryGroupTraceReasonHashFocus,
    notificationBatchRetrySubmitting,
    notificationTraceSloScanColumns,
    notificationTraceSloScanConcurrency,
    notificationTraceSloScanDisplayedItems,
    notificationTraceSloScanDryRun,
    notificationTraceSloScanLookbackHours,
    notificationTraceSloScanMarkdownText,
    notificationTraceSloScanMaxGroups,
    notificationTraceSloScanMobileColumns,
    notificationTraceSloScanModalOpen,
    notificationTraceSloScanQuickFilter,
    notificationTraceSloScanRankedItems,
    notificationTraceSloScanResult,
    notificationTraceSloScanRiskSummary,
    notificationTraceSloScanRunning,
    openBatchHistoryAlertModal,
    openNotifyTraceSloScanAlertModal,
    resetBatchHistoryFilters,
    retryableFailedCount,
    retryCurrentTraceFailedNotifications,
    retryCurrentTraceRetryableNotifications,
    retryFilteredBatchHistoryByCurrentGroups,
    retryGroupTraceColumns,
    retryGroupTraceErrorMessage,
    retryGroupTraceEvents,
    retryGroupTraceFailedEvents,
    retryGroupTraceFilter,
    retryGroupTraceIsFetching,
    retryGroupTraceMarkdownText,
    retryGroupTraceModalOpen,
    retryGroupTraceReasonHashFocusLabel,
    retryGroupTraceReasonHashRecovery,
    retryGroupTraceReasonHashRecoverySummary,
    retryGroupTraceRetryableFailedEvents,
    retryGroupTraceSloDescription,
    retryGroupTraceSloStatus,
    retryGroupTraceSource,
    retryGroupTraceSummary,
    retryLastFailedBatch,
    retryLastRetryableFailedBatch,
    runNotificationTraceSloScan,
    runtimeDetailDrawerOpen,
    runtimeStoreDerivedState,
    runtimeWarnings,
    setBatchHistoryActionFilter,
    setBatchHistoryFailureFilter,
    setBatchHistoryKeyword,
    setBatchHistoryTimeRangeFilter,
    setBatchResultFilter,
    setNotificationTraceSloScanConcurrency,
    setNotificationTraceSloScanDryRun,
    setNotificationTraceSloScanLookbackHours,
    setNotificationTraceSloScanMaxGroups,
    setNotificationTraceSloScanQuickFilter,
    setRetryGroupTraceFilter,
    setRuntimeDetailDrawerOpen,
    submitBatchHistoryAlertModal,
    triggerForm,
    triggerModalPipeline,
    triggerModalSpecs,
  } = props;

  return (
    <>
      <DataOpsRuntimeDrawer
        open={runtimeDetailDrawerOpen}
        compact={isCompactViewport}
        onClose={() => setRuntimeDetailDrawerOpen(false)}
        {...runtimeStoreDerivedState}
        runtimeWarnings={runtimeWarnings}
      />

      <DataOpsBatchModals
        batchHistoryOpen={batchHistoryModalOpen}
        batchHistoryItems={batchExecutionHistory}
        filteredBatchHistoryItems={filteredBatchHistoryItems}
        batchHistoryActionFilter={batchHistoryActionFilter}
        batchHistoryFailureFilter={batchHistoryFailureFilter}
        batchHistoryTimeRangeFilter={batchHistoryTimeRangeFilter}
        batchHistoryKeyword={batchHistoryKeyword}
        batchHistoryMarkdownText={batchHistoryMarkdownText}
        batchHistoryFailedPipelineCount={filteredBatchHistoryFailedPipelineIds.length}
        batchHistoryRetryableFailedPipelineCount={filteredBatchHistoryRetryableFailedPipelineIds.length}
        batchHistoryRetryGroupCount={filteredBatchHistoryRetryGroups.length}
        batchHistoryRetryableGroupCount={filteredBatchHistoryRetryableGroups.length}
        batchHistoryFailureSummary={batchHistoryFailureSummary}
        batchHistoryFailureSummaryText={batchHistoryFailureSummaryText}
        batchHistoryAlertTemplateText={batchHistoryAlertTemplateText}
        batchHistoryAlertTooltipTitle={
          defaultAlertChannel
            ? `默认通道：${defaultAlertChannel.channelName}（点击可选择）`
            : '当前没有可用通道'
        }
        batchHistoryAlertDisabled={
          !hasOperatePermission ||
          globalActionBusy ||
          !batchHistoryAlertTemplateText ||
          !defaultAlertChannel
        }
        batchHistoryColumns={isCompactViewport ? batchHistoryMobileColumns : batchHistoryColumns}
        batchHistoryAlertOpen={batchHistoryAlertModalOpen}
        batchHistoryAlertCopy={batchHistoryAlertModalCopy}
        batchHistoryAlertSubmitting={batchHistoryAlertSubmitting}
        batchHistoryAlertForm={batchHistoryAlertForm}
        availableAlertChannels={availableAlertChannels}
        batchResultOpen={batchResultModalOpen}
        batchResultSummary={lastBatchExecutionSummary}
        batchResultFilter={batchResultFilter}
        batchResultFailedPipelineCount={batchResultFailedPipelineIds.length}
        batchResultRetryableFailedCount={batchResultRetryableFailedCount}
        batchResultFilteredItems={filteredBatchResultItems}
        batchResultColumns={isCompactViewport ? batchResultMobileColumns : batchResultColumns}
        lastBatchFailureContext={lastBatchFailureContext}
        retryableFailedCount={retryableFailedCount}
        hasOperatePermission={hasOperatePermission}
        globalActionBusy={globalActionBusy}
        isCompactViewport={isCompactViewport}
        onCloseBatchHistory={closeBatchHistoryModal}
        onBatchHistoryActionFilterChange={setBatchHistoryActionFilter}
        onBatchHistoryFailureFilterChange={setBatchHistoryFailureFilter}
        onBatchHistoryTimeRangeFilterChange={setBatchHistoryTimeRangeFilter}
        onBatchHistoryKeywordChange={setBatchHistoryKeyword}
        onExportBatchHistoryCsv={exportFilteredBatchHistoryCsv}
        onCopyBatchHistoryMarkdown={() =>
          copyTextToClipboard(batchHistoryMarkdownText, '批量历史Markdown报告')
        }
        onCopyBatchHistoryFailedPipelineIds={copyFilteredBatchHistoryFailedPipelineIds}
        onRetryFilteredBatchHistory={retryFilteredBatchHistoryByCurrentGroups}
        onResetBatchHistoryFilters={resetBatchHistoryFilters}
        onCopy={copyTextToClipboard}
        onOpenBatchHistoryAlert={openBatchHistoryAlertModal}
        onApplyBatchHistoryReasonFilter={applyBatchHistoryReasonFilter}
        onCloseBatchHistoryAlert={closeBatchHistoryAlertModal}
        onSubmitBatchHistoryAlert={submitBatchHistoryAlertModal}
        onCloseBatchResult={closeBatchResultModal}
        onRetryLastRetryableFailedBatch={retryLastRetryableFailedBatch}
        onRetryLastFailedBatch={retryLastFailedBatch}
        onBatchResultFilterChange={setBatchResultFilter}
        onCopyBatchResultFailedPipelineIds={copyBatchFailedPipelineIds}
      />

      <DataOpsNotificationTraceModals
        notificationTraceSloScanOpen={notificationTraceSloScanModalOpen}
        notificationTraceSloScanDryRun={notificationTraceSloScanDryRun}
        notificationTraceSloScanRunning={notificationTraceSloScanRunning}
        notificationTraceSloScanLookbackHours={notificationTraceSloScanLookbackHours}
        notificationTraceSloScanMaxGroups={notificationTraceSloScanMaxGroups}
        notificationTraceSloScanConcurrency={notificationTraceSloScanConcurrency}
        notificationTraceSloScanResult={notificationTraceSloScanResult}
        notificationTraceSloScanRiskSummary={notificationTraceSloScanRiskSummary}
        notificationTraceSloScanQuickFilter={notificationTraceSloScanQuickFilter}
        notificationTraceSloScanRankedItems={notificationTraceSloScanRankedItems}
        notificationTraceSloScanDisplayedItems={notificationTraceSloScanDisplayedItems}
        notificationTraceSloScanMarkdownText={notificationTraceSloScanMarkdownText}
        notificationTraceSloScanColumns={
          isCompactViewport ? notificationTraceSloScanMobileColumns : notificationTraceSloScanColumns
        }
        defaultAlertChannel={defaultAlertChannel}
        retryGroupTraceOpen={retryGroupTraceModalOpen}
        activeRetryGroupTraceId={activeRetryGroupTraceId}
        retryGroupTraceEvents={retryGroupTraceEvents}
        filteredRetryGroupTraceEvents={filteredRetryGroupTraceEvents}
        retryGroupTraceFailedEvents={retryGroupTraceFailedEvents}
        retryGroupTraceRetryableFailedEvents={retryGroupTraceRetryableFailedEvents}
        retryGroupTraceSummary={retryGroupTraceSummary}
        retryGroupTraceIsFetching={retryGroupTraceIsFetching}
        retryGroupTraceErrorMessage={retryGroupTraceErrorMessage}
        retryGroupTraceSource={retryGroupTraceSource}
        retryGroupTraceSloStatus={retryGroupTraceSloStatus}
        retryGroupTraceSloDescription={retryGroupTraceSloDescription}
        retryGroupTraceReasonHashRecovery={retryGroupTraceReasonHashRecovery}
        retryGroupTraceReasonHashRecoverySummary={retryGroupTraceReasonHashRecoverySummary}
        normalizedRetryGroupTraceReasonHashFocus={normalizedRetryGroupTraceReasonHashFocus}
        retryGroupTraceReasonHashFocusLabel={retryGroupTraceReasonHashFocusLabel}
        retryGroupTraceFilter={retryGroupTraceFilter}
        retryGroupTraceMarkdownText={retryGroupTraceMarkdownText}
        retryGroupTraceColumns={retryGroupTraceColumns}
        hasOperatePermission={hasOperatePermission}
        globalActionBusy={globalActionBusy}
        notificationBatchRetrySubmitting={notificationBatchRetrySubmitting}
        isCompactViewport={isCompactViewport}
        onCloseNotificationTraceSloScan={closeNotificationTraceSloScanModal}
        onRunNotificationTraceSloScan={runNotificationTraceSloScan}
        onNotificationTraceSloScanDryRunChange={setNotificationTraceSloScanDryRun}
        onNotificationTraceSloScanLookbackHoursChange={setNotificationTraceSloScanLookbackHours}
        onNotificationTraceSloScanMaxGroupsChange={setNotificationTraceSloScanMaxGroups}
        onNotificationTraceSloScanConcurrencyChange={setNotificationTraceSloScanConcurrency}
        onNotificationTraceSloScanQuickFilterChange={setNotificationTraceSloScanQuickFilter}
        onCopyNotificationTraceSloScanMarkdown={copyNotificationTraceSloScanMarkdown}
        onOpenNotifyTraceSloScanAlert={openNotifyTraceSloScanAlertModal}
        onCloseRetryGroupTrace={closeRetryGroupTraceModal}
        onFocusRetryGroupTraceReasonHash={focusRetryGroupTraceByReasonHash}
        onRetryGroupTraceFilterChange={setRetryGroupTraceFilter}
        onRetryCurrentTraceFailedNotifications={retryCurrentTraceFailedNotifications}
        onRetryCurrentTraceRetryableNotifications={retryCurrentTraceRetryableNotifications}
        onApplyRetryGroupTraceAsNotifyFilter={applyRetryGroupTraceAsNotifyFilter}
        onCopyRetryGroupTraceLink={copyRetryGroupTraceLink}
        onCopyRetryGroupTraceMarkdown={copyRetryGroupTraceMarkdown}
        onExportRetryGroupTraceCsv={exportRetryGroupTraceCsv}
        onClearRetryGroupTraceReasonHashFocus={clearRetryGroupTraceReasonHashFocus}
      />

      <DataOpsTriggerCommandModals
        triggerPipeline={triggerModalPipeline}
        triggerForm={triggerForm}
        triggerSpecs={triggerModalSpecs}
        triggerSubmitting={isTriggerModalSubmitting}
        batchTriggerPipelineIds={batchTriggerModalPipelineIds}
        batchTriggerForm={batchTriggerForm}
        batchTriggerPipelines={batchTriggerModalPipelines}
        batchTriggerSpecs={batchTriggerModalSpecs}
        batchTriggerExecutionPreview={batchTriggerExecutionPreview}
        batchTriggerSubmitting={isBatchTriggerModalSubmitting}
        commandPipeline={commandModalPipeline}
        commandForm={commandForm}
        commandSpecs={commandModalSpecs}
        commandPreview={commandModalCommandPreview}
        isCompactViewport={isCompactViewport}
        onCloseTrigger={closeTriggerModal}
        onSubmitTrigger={handleTriggerWithParameters}
        onCloseBatchTrigger={closeBatchTriggerModal}
        onSubmitBatchTrigger={handleBatchTriggerWithParameters}
        onCloseCommand={closeCommandModal}
        onCopy={copyTextToClipboard}
      />
    </>
  );
}
