import type { DataOpsHubClientState } from './dataops-hub-client-state-contract';

const DATAOPS_HUB_TAB_CONTENT_PROP_KEYS = [
  'activeFeishuSyncJobKey',
  'activeTab',
  'applyAudit24hFailed',
  'applyAudit7dFailed',
  'applyAuditFailedOnly',
  'applyNotifyReasonFilter',
  'applyQuickPipelineSelection',
  'auditActionFilter',
  'auditActionOptions',
  'auditColumns',
  'auditEvents',
  'auditMobileColumns',
  'auditResultFilter',
  'auditTimeRangeFilter',
  'batchActionKey',
  'batchExecutionHistory',
  'channelColumns',
  'channelFilter',
  'channelHealthSummary',
  'channelMobileColumns',
  'copyCurrentNotifyFilterLink',
  'copyFilteredFailedNotificationEventIds',
  'copyTextToClipboard',
  'defaultAlertChannel',
  'exportFilteredNotificationEventsCsv',
  'exportNotificationRetryReportCsv',
  'feishuSyncStatusSummary',
  'filteredAudits',
  'filteredEvents',
  'filteredFailedNotificationEventIds',
  'filteredFailedNotificationEvents',
  'filteredPipelines',
  'filteredRetryableFailedNotificationEvents',
  'globalActionBusy',
  'handleBatchOperation',
  'handleFeishuSyncJobAction',
  'hasOperatePermission',
  'hasPipelineFilter',
  'isAudit24hFailed',
  'isAudit7dFailed',
  'isAuditFailedOnly',
  'isCompactViewport',
  'keywordFilterText',
  'lastBatchExecutionSummary',
  'lastBatchFailureContext',
  'notificationBatchRetrySubmitting',
  'notificationChannelSelectOptions',
  'notificationColumns',
  'notificationEventTypeFilter',
  'notificationEventTypeOptions',
  'notificationEvents',
  'notificationFailureAlertTemplateText',
  'notificationFailureSummary',
  'notificationFailureSummaryText',
  'notificationMarkdownText',
  'notificationMobileColumns',
  'notificationRetryConcurrency',
  'notificationRetryReport',
  'notificationStatusFilter',
  'notificationTraceSloScanRunning',
  'notifyFailureChannelFocus',
  'notifyFailureChannelOptions',
  'notifyReasonHashFilter',
  'notifyRetryGroupIdFilter',
  'openBatchHistoryModal',
  'openBatchResultModal',
  'openBatchTriggerModal',
  'openChannelManualNotifyModal',
  'openNotificationTraceSloScanModal',
  'openNotifyFailureSummaryAlertModal',
  'openNotifyMarkdownAlertModal',
  'openRetryGroupTraceModalById',
  'orderedNotificationChannels',
  'pipelineColumns',
  'pipelineMobileColumns',
  'prioritizedFeishuSyncJobs',
  'prioritizedStreams',
  'renderNotificationExpandedRow',
  'renderPaginationTotal',
  'renderPipelineExpandedRow',
  'resetAuditFilters',
  'resetNotifyFilters',
  'retryableFailedCount',
  'retryFilteredFailedNotifications',
  'retryLastFailedBatch',
  'retryLastRetryableFailedBatch',
  'retrySelectedNotifyFailureReason',
  'selectedNotifyFailureReason',
  'selectedPipelineIds',
  'selectedReasonFailedNotificationEvents',
  'selectedReasonRetryableFailedNotificationEvents',
  'setAuditActionFilter',
  'setAuditResultFilter',
  'setAuditTimeRangeFilter',
  'setChannelFilter',
  'setKeywordInput',
  'setNotificationEventTypeFilter',
  'setNotificationRetryConcurrency',
  'setNotificationStatusFilter',
  'setNotifyFailureChannelFocus',
  'setNotifyReasonHashFilter',
  'setNotifyRetryGroupIdFilter',
  'setSelectedNotifyFailureReason',
  'setSelectedPipelineIds',
  'setStatusFilter',
  'statusFilterLabel',
  'syncStatusSummary',
] as const satisfies readonly (keyof DataOpsHubClientState)[];

export type DataOpsHubTabContentProps = Pick<
  DataOpsHubClientState,
  (typeof DATAOPS_HUB_TAB_CONTENT_PROP_KEYS)[number]
>;

export function pickDataOpsHubTabContentProps(
  state: DataOpsHubClientState,
): DataOpsHubTabContentProps {
  return Object.fromEntries(
    DATAOPS_HUB_TAB_CONTENT_PROP_KEYS.map((key) => [key, state[key]]),
  ) as DataOpsHubTabContentProps;
}
