/**
 * 用户管理页面
 *
 * 功能：
 * - 列表展示所有用户
 * - 创建新用户
 * - 编辑用户信息
 * - 删除用户（软删除）
 * - 管理用户角色
 *
 * 权限要求：user:list:all
 */

'use client';

import { useState, useCallback, useMemo } from 'react';
import {
  App,
  Alert,
  Table,
  Button,
  Form,
  Spin,
  Card,
} from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import { ProtectedRoute } from '@/components/protected-route';
import { Layout } from '@/components/organisms/layout';
import { useIsMobile } from '@/hooks/use-media-query';
import { ADMIN_READ_PERMISSIONS } from '@/lib/permissions';
import { useBackendCapabilities } from '@/hooks/use-backend-capabilities';
import { isReservedElevatedRoleCode, isSuperAdminByRoleOrIdentity } from '@/lib/role-access';
import { useAuthStore } from '@/stores/auth.store';
import type { User, UserFormValues } from '../_lib/users-types';
import { UserFormModal } from './user-form-modal';
import { UserRoleAssignmentModal } from './user-role-assignment-modal';
import { buildAutoGeneratedEmail } from './user-email-helpers';
import { UsersMobileList } from './users-mobile-list';
import { useUsersPageActions } from './users-page-actions';
import { useUsersPageListState } from './users-page-list-state';
import { useUsersRoleAssignmentState } from './users-role-assignment-state';
import { buildUsersTableColumns } from './users-table-columns';

/**
 * 用户管理页面
 */
export function UsersPageClient() {
  const { message: messageApi } = App.useApp();
  const isMobile = useIsMobile();
  const currentUser = useAuthStore((state) => state.user);
  const { data: backendCapabilities, isLoading: isCapabilitiesLoading } = useBackendCapabilities();
  const supportsUsersApi = backendCapabilities?.modules?.users ?? backendCapabilities?.supportsAdminApis ?? false;
  const canManageElevatedRoles = useMemo(
    () =>
      isSuperAdminByRoleOrIdentity(currentUser?.roles || [], {
        username: currentUser?.username,
        email: currentUser?.email,
        fullName: currentUser?.full_name,
      }),
    [currentUser?.email, currentUser?.full_name, currentUser?.roles, currentUser?.username]
  );
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [editingUser, setEditingUser] = useState<User | null>(null);
  const [form] = Form.useForm<UserFormValues>();

  const {
    userList,
    isLoading,
    mobilePageSize,
    mobilePaginationCurrent,
    mobilePagedUsers,
    handleMobilePaginationChange,
  } = useUsersPageListState({
    supportsUsersApi,
  });

  const {
    roleModalUser,
    roleListItems,
    roleItems,
    roleOptions,
    selectedRoleIds,
    roleEditBlocked,
    isRoleListLoading,
    isRoleSelectionLoading,
    setSelectedRoleIds,
    setRoleModalUser,
    handleOpenRoleModal,
    handleCancelRoleModal,
  } = useUsersRoleAssignmentState({
    supportsUsersApi,
    canManageElevatedRoles,
  });

  const {
    createUserMutation,
    deleteUserMutation,
    updateUserMutation,
    updateUserRolesMutation,
  } = useUsersPageActions({
    messageApi,
    form,
    editingUser,
    setIsModalVisible,
    setEditingUser,
    setRoleModalUser,
    setSelectedRoleIds,
  });

  /**
   * 打开创建用户对话框
   */
  const handleCreate = useCallback(() => {
    setEditingUser(null);
    form.resetFields();
    setIsModalVisible(true);
  }, [form]);

  /**
   * 打开编辑对话框
   */
  const handleEdit = useCallback((user: User) => {
    setEditingUser(user);
    form.setFieldsValue(user);
    setIsModalVisible(true);
  }, [form]);

  /**
   * 提交表单
   */
  const handleSubmit = async (values: UserFormValues) => {
    if (editingUser) {
      updateUserMutation.mutate(values);
    } else {
      const username = typeof values.username === 'string' ? values.username.trim() : '';
      const password = typeof values.password === 'string' ? values.password : '';
      const email =
        typeof values.email === 'string' && values.email.trim()
          ? values.email.trim()
          : buildAutoGeneratedEmail(username);

      createUserMutation.mutate({
        ...values,
        username,
        password,
        email,
      });
    }
  };

  /**
   * 关闭对话框
   */
  const handleCancel = () => {
    setIsModalVisible(false);
    setEditingUser(null);
    form.resetFields();
  };

  const handleDeleteUser = useCallback(
    (user: User) => {
      deleteUserMutation.mutate(user.id);
    },
    [deleteUserMutation]
  );

  const columns = useMemo(
    () =>
      buildUsersTableColumns({
        onDelete: handleDeleteUser,
        onEdit: handleEdit,
        onOpenRoleModal: handleOpenRoleModal,
      }),
    [handleDeleteUser, handleEdit, handleOpenRoleModal]
  );

  const handleSubmitRoleModal = useCallback(() => {
    if (!roleModalUser) {
      return;
    }

    if (roleEditBlocked) {
      messageApi.error('仅超级管理员可维护包含 admin/super_admin 的用户角色。');
      return;
    }

    const includesElevatedRole = selectedRoleIds.some((roleId) => {
      const role = roleListItems.find((item) => String(item.id) === roleId);
      return role ? isReservedElevatedRoleCode(role.code) : false;
    });

    if (!canManageElevatedRoles && includesElevatedRole) {
      messageApi.error('仅超级管理员可授予 admin/super_admin 角色。');
      return;
    }

    updateUserRolesMutation.mutate({
      userId: roleModalUser.id,
      roleIds: selectedRoleIds,
    });
  }, [
    canManageElevatedRoles,
    messageApi,
    roleEditBlocked,
    roleListItems,
    roleModalUser,
    selectedRoleIds,
    updateUserRolesMutation,
  ]);

  return (
    <ProtectedRoute requiredPermission={ADMIN_READ_PERMISSIONS} permissionMode="any">
      <Layout>
        {!isCapabilitiesLoading && !supportsUsersApi ? (
          <Card title="用户管理">
            <Alert
              type="info"
              showIcon
              title="当前后端未启用用户管理接口"
              description={`检测到后端：${backendCapabilities?.backendName || 'unknown'}。当前环境的用户管理接口不可用，用户列表与增删改操作已自动降级。`}
            />
          </Card>
        ) : null}
        {isCapabilitiesLoading ? (
          <Card title="用户管理">
            <Spin />
          </Card>
        ) : null}
        {!isCapabilitiesLoading && supportsUsersApi ? (
        <Card title="用户管理" extra={<Button type="primary" icon={<PlusOutlined />} onClick={handleCreate}>新建用户</Button>}>
          {isLoading ? (
            <Spin />
          ) : isMobile ? (
            <UsersMobileList
              users={mobilePagedUsers}
              current={mobilePaginationCurrent}
              pageSize={mobilePageSize}
              total={userList.total}
              onChange={handleMobilePaginationChange}
              onEdit={handleEdit}
              onOpenRoleModal={handleOpenRoleModal}
              onDelete={handleDeleteUser}
            />
          ) : (
            <Table
              columns={columns}
              dataSource={userList.items}
              rowKey="id"
              pagination={{ pageSize: 20, total: userList.total }}
              scroll={{ x: 1200 }}
            />
          )}

          <UserFormModal
            form={form}
            user={editingUser}
            open={isModalVisible}
            isSaving={createUserMutation.isPending || updateUserMutation.isPending}
            onSubmit={handleSubmit}
            onCancel={handleCancel}
          />

          <UserRoleAssignmentModal
            user={roleModalUser}
            roleItems={roleItems}
            roleOptions={roleOptions}
            selectedRoleIds={selectedRoleIds}
            canManageElevatedRoles={canManageElevatedRoles}
            roleEditBlocked={roleEditBlocked}
            isRoleListLoading={isRoleListLoading}
            isRoleSelectionLoading={isRoleSelectionLoading}
            isSaving={updateUserRolesMutation.isPending}
            onSubmit={handleSubmitRoleModal}
            onCancel={handleCancelRoleModal}
            onSelectedRoleIdsChange={setSelectedRoleIds}
          />
        </Card>
        ) : null}
      </Layout>
    </ProtectedRoute>
  );
}
