const AUTO_GENERATED_EMAIL_DOMAIN = 'users.local';

export function buildAutoGeneratedEmail(username: string): string {
  const normalized = username.trim().toLowerCase();
  const sanitized = normalized
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^[^a-z0-9]+/, '')
    .replace(/[^a-z0-9]+$/, '');
  const localPart = sanitized || `user-${Date.now()}`;
  return `${localPart}@${AUTO_GENERATED_EMAIL_DOMAIN}`;
}

function isAutoGeneratedEmail(email?: string): boolean {
  if (!email) {
    return false;
  }

  const normalized = email.trim().toLowerCase();
  return normalized.endsWith(`@${AUTO_GENERATED_EMAIL_DOMAIN}`);
}

export function getDisplayEmail(email?: string): string {
  if (!email || isAutoGeneratedEmail(email)) {
    return '-';
  }
  return email;
}
