use serde::Serialize;
use sqlx::{postgres::PgRow, Decode, Postgres, Row, Type};

#[derive(Serialize)]
pub(super) struct LiveDetailRowFields {
    #[serde(skip_serializing)]
    pub(super) live_identity_type: String,
    pub(super) anchor_douyin_id: String,
    pub(super) anchor_nickname: String,
    pub(super) anchor_type: String,
    pub(super) shop_name: String,
    pub(super) shop_id: String,
    pub(super) stat_date: String,
    pub(super) live_start_time: String,
    pub(super) live_end_time: Option<String>,
    pub(super) live_session_count: i64,
    pub(super) live_duration_minutes: i64,
    pub(super) live_exposure_user_count: i64,
    pub(super) live_exposure_count: i64,
    pub(super) live_gmv: f64,
    pub(super) live_user_pay_amount: f64,
    pub(super) hourly_user_pay_amount: f64,
    pub(super) live_buyer_count: i64,
    pub(super) live_sale_quantity: i64,
    pub(super) live_watch_user_count: i64,
    pub(super) hourly_watch_user_count: i64,
    pub(super) live_watch_count: i64,
    pub(super) max_online_count: i64,
    pub(super) avg_online_count: f64,
    pub(super) avg_watch_duration_minutes: f64,
    pub(super) comment_count: i64,
    pub(super) new_live_group_count: i64,
    pub(super) new_follower_count: i64,
    pub(super) unfollow_count: i64,
    pub(super) old_follower_watch_rate: f64,
    pub(super) product_count: i64,
    pub(super) live_product_exposure_user: i64,
    pub(super) live_product_click_user: i64,
    pub(super) live_product_exposure_count: i64,
    pub(super) live_product_click_count: i64,
    pub(super) live_order_count: i64,
    pub(super) live_refund_order_count: i64,
    pub(super) live_refund_amount: f64,
    pub(super) live_refund_user_count: i64,
    pub(super) estimated_commission: f64,
    pub(super) product_click_rate_count: f64,
    pub(super) product_click_rate_user: f64,
    pub(super) click_to_pay_rate_count: f64,
    pub(super) click_to_pay_rate_user: f64,
    pub(super) watch_to_pay_rate_count: f64,
    pub(super) watch_to_pay_rate_user: f64,
    pub(super) presale_order_count: i64,
    pub(super) presale_full_amount: f64,
    pub(super) new_cart_group_count: i64,
    pub(super) live_ad_cost: f64,
    pub(super) net_gmv: f64,
    pub(super) net_order_count: i64,
    pub(super) refund_amount_1h: f64,
    pub(super) refund_order_count_1h: i64,
    pub(super) refund_rate_1h: f64,
    pub(super) coupon_guided_payment_amount: f64,
    pub(super) coupon_guided_payment_rate: f64,
    pub(super) coupon_subsidy_amount: f64,
    pub(super) coupon_usage_count: f64,
    pub(super) ad_cost_shop_bound: f64,
    pub(super) ad_cost_shop_targeted: f64,
    pub(super) refund_rate: Option<f64>,
}

impl LiveDetailRowFields {
    pub(super) fn from_row(row: &PgRow) -> Result<Self, String> {
        Ok(Self {
            live_identity_type: get(row, "live_identity_type")?,
            anchor_douyin_id: get(row, "anchor_douyin_id")?,
            anchor_nickname: get(row, "anchor_nickname")?,
            anchor_type: get(row, "anchor_type")?,
            shop_name: get(row, "shop_name")?,
            shop_id: get(row, "shop_id")?,
            stat_date: get(row, "stat_date")?,
            live_start_time: get(row, "live_start_time")?,
            live_end_time: get(row, "live_end_time")?,
            live_session_count: get(row, "live_session_count")?,
            live_duration_minutes: get(row, "live_duration_minutes")?,
            live_exposure_user_count: get(row, "live_exposure_user_count")?,
            live_exposure_count: get(row, "live_exposure_count")?,
            live_gmv: get(row, "live_gmv")?,
            live_user_pay_amount: get(row, "live_user_pay_amount")?,
            hourly_user_pay_amount: get(row, "hourly_user_pay_amount")?,
            live_buyer_count: get(row, "live_buyer_count")?,
            live_sale_quantity: get(row, "live_sale_quantity")?,
            live_watch_user_count: get(row, "live_watch_user_count")?,
            hourly_watch_user_count: get(row, "hourly_watch_user_count")?,
            live_watch_count: get(row, "live_watch_count")?,
            max_online_count: get(row, "max_online_count")?,
            avg_online_count: get(row, "avg_online_count")?,
            avg_watch_duration_minutes: get(row, "avg_watch_duration_minutes")?,
            comment_count: get(row, "comment_count")?,
            new_live_group_count: get(row, "new_live_group_count")?,
            new_follower_count: get(row, "new_follower_count")?,
            unfollow_count: get(row, "unfollow_count")?,
            old_follower_watch_rate: get(row, "old_follower_watch_rate")?,
            product_count: get(row, "product_count")?,
            live_product_exposure_user: get(row, "live_product_exposure_user")?,
            live_product_click_user: get(row, "live_product_click_user")?,
            live_product_exposure_count: get(row, "live_product_exposure_count")?,
            live_product_click_count: get(row, "live_product_click_count")?,
            live_order_count: get(row, "live_order_count")?,
            live_refund_order_count: get(row, "live_refund_order_count")?,
            live_refund_amount: get(row, "live_refund_amount")?,
            live_refund_user_count: get(row, "live_refund_user_count")?,
            estimated_commission: get(row, "estimated_commission")?,
            product_click_rate_count: get(row, "product_click_rate_count")?,
            product_click_rate_user: get(row, "product_click_rate_user")?,
            click_to_pay_rate_count: get(row, "click_to_pay_rate_count")?,
            click_to_pay_rate_user: get(row, "click_to_pay_rate_user")?,
            watch_to_pay_rate_count: get(row, "watch_to_pay_rate_count")?,
            watch_to_pay_rate_user: get(row, "watch_to_pay_rate_user")?,
            presale_order_count: get(row, "presale_order_count")?,
            presale_full_amount: get(row, "presale_full_amount")?,
            new_cart_group_count: get(row, "new_cart_group_count")?,
            live_ad_cost: get(row, "live_ad_cost")?,
            net_gmv: get(row, "net_gmv")?,
            net_order_count: get(row, "net_order_count")?,
            refund_amount_1h: get(row, "refund_amount_1h")?,
            refund_order_count_1h: get(row, "refund_order_count_1h")?,
            refund_rate_1h: get(row, "refund_rate_1h")?,
            coupon_guided_payment_amount: get(row, "coupon_guided_payment_amount")?,
            coupon_guided_payment_rate: get(row, "coupon_guided_payment_rate")?,
            coupon_subsidy_amount: get(row, "coupon_subsidy_amount")?,
            coupon_usage_count: get(row, "coupon_usage_count")?,
            ad_cost_shop_bound: get(row, "ad_cost_shop_bound")?,
            ad_cost_shop_targeted: get(row, "ad_cost_shop_targeted")?,
            refund_rate: get(row, "refund_rate")?,
        })
    }
}

fn get<T>(row: &PgRow, column: &'static str) -> Result<T, String>
where
    for<'row> T: Decode<'row, Postgres> + Type<Postgres>,
{
    row.try_get::<T, _>(column)
        .map_err(|error| error.to_string())
}
