#[derive(Debug, Clone)]
pub(super) struct DashboardLiveGoodsMetricRow {
    pub(super) stat_date: String,
    pub(super) live_start_time: String,
    pub(super) live_end_time: Option<String>,
    pub(super) anchor_douyin_id: String,
    pub(super) anchor_nickname: String,
    pub(super) anchor_type: String,
    pub(super) shop_id: String,
    pub(super) shop_name: String,
    pub(super) live_identity_type: String,
    pub(super) live_duration_minutes: f64,
    pub(super) product_name: String,
    pub(super) product_id: String,
    pub(super) sku_name: String,
    pub(super) sku_row_type: String,
    pub(super) product_image_url: String,
    pub(super) product_user_pay_amount: f64,
    pub(super) product_sales_volume: f64,
    pub(super) product_buyer_count: f64,
    pub(super) product_order_count: f64,
    pub(super) presale_order_count: f64,
    pub(super) presale_full_amount: f64,
    pub(super) product_exposure_user_count: f64,
    pub(super) product_click_user_count: f64,
    pub(super) product_exposure_to_click_rate_user: f64,
    pub(super) product_click_to_pay_rate_user: f64,
    pub(super) refund_user_count: f64,
    pub(super) refund_amount: f64,
    pub(super) refund_order_count: f64,
}
