export interface DouyinLiveSessionRow {
  rowId: string;
  sessionId: string;
  shopName: string;
  shopId: string;
  anchorNickname: string;
  anchorDouyinId: string;
  liveStartTime: string;
  liveEndTime: string;
  currLiveDurationMinutes: number;
  prevLiveDurationMinutes: number;
  currLiveExposureUserCount: number;
  prevLiveExposureUserCount: number;
  currLiveWatchUserCount: number;
  prevLiveWatchUserCount: number;
  currLiveProductExposureUser: number;
  prevLiveProductExposureUser: number;
  currLiveProductClickUser: number;
  prevLiveProductClickUser: number;
  currLiveBuyerCount: number;
  prevLiveBuyerCount: number;
  currLiveOrderCount: number;
  prevLiveOrderCount: number;
  currLiveGmv: number;
  prevLiveGmv: number;
  liveGmvDelta: number;
  currLiveUserPayAmount: number;
  prevLiveUserPayAmount: number;
  currLiveAdCost: number;
  prevLiveAdCost: number;
  currCommentCount: number;
  prevCommentCount: number;
  currNewFollowerCount: number;
  prevNewFollowerCount: number;
  currProductCount: number;
  prevProductCount: number;
  currAvgOrderValue: number | undefined;
  prevAvgOrderValue: number | undefined;
}
