#[derive(Debug)]
pub(in crate::marketing) struct NormalizedQuery {
    pub(in crate::marketing) keyword: Option<String>,
    pub(in crate::marketing) platform: Option<String>,
    pub(in crate::marketing) category: Option<String>,
    pub(in crate::marketing) anchor_tags: Vec<String>,
    pub(in crate::marketing) fans_band: Option<String>,
    pub(in crate::marketing) anchor_level: Option<String>,
    pub(in crate::marketing) cooperation_status: Option<String>,
    pub(in crate::marketing) owner_name: Option<String>,
    pub(in crate::marketing) owner_user_id: Option<String>,
    pub(in crate::marketing) last_follow_range: Option<String>,
    pub(in crate::marketing) is_cooperable: Option<bool>,
    pub(in crate::marketing) source_type: Option<String>,
    pub(in crate::marketing) ownership: Option<String>,
    pub(in crate::marketing) mcn_status: Option<String>,
    pub(in crate::marketing) include_filter_options: bool,
    pub(in crate::marketing) include_summary: bool,
    pub(in crate::marketing) page: i64,
    pub(in crate::marketing) page_size: i64,
    pub(in crate::marketing) sort: CreatorLibrarySort,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(in crate::marketing) enum CreatorLibrarySort {
    OwnerPriorityDesc,
    UpdatedDesc,
    UpdatedAsc,
    IdentityAsc,
    IdentityDesc,
    NameAsc,
    NameDesc,
    PlatformAsc,
    PlatformDesc,
    FansDesc,
    FansAsc,
    AnchorTagAsc,
    AnchorTagDesc,
    AnchorLevelAsc,
    AnchorLevelDesc,
    Sales30dDesc,
    Sales30dAsc,
    Sales90dDesc,
    Sales90dAsc,
    StatusAsc,
    StatusDesc,
    OwnerAsc,
    OwnerDesc,
    LastFollowAsc,
    LastFollowDesc,
}
