import type {
  DashboardLiveDetailRow,
  GoodsCardColumnDefinition,
  GoodsCardTrafficMetricDefinition,
  LiveDetailMetricDefinition,
  LiveScope,
  ShortVideoScope,
  TrafficGoodsMetricDefinition,
  TrafficMetricDefinition,
} from './dashboard-types';

export const TRAFFIC_METRIC_DEFINITIONS: TrafficMetricDefinition[] = [
  { key: 'visitorCount', title: '访客数', format: 'integer' },
  { key: 'newVisitorCount', title: '新访客数', format: 'integer' },
  { key: 'productClickUserCount', title: '商品点击人数', format: 'integer' },
  { key: 'payBuyerCount', title: '支付买家数', format: 'integer' },
  { key: 'payAmount', title: '支付金额', format: 'currency' },
  { key: 'followShopUserCount', title: '关注店铺人数', format: 'integer' },
  { key: 'productFavoriteUserCount', title: '商品收藏人数', format: 'integer' },
  { key: 'cartUserCount', title: '加购人数', format: 'integer' },
  { key: 'cartCount', title: '加购件数', format: 'integer' },
  { key: 'payConversionRate', title: '支付转化率', format: 'rate' },
  { key: 'uvValue', title: 'UV价值', format: 'number', digits: 2 },
  { key: 'avgOrderValue', title: '客单价', format: 'currency' },
  { key: 'avgStayDuration', title: '平均停留时长', format: 'number', digits: 1 },
  { key: 'view3sUserCount', title: '3s查看人数', format: 'integer' },
];

export const TRAFFIC_GOODS_METRIC_DEFINITIONS: TrafficGoodsMetricDefinition[] = [
  { key: 'visitorCount', title: '访客数', format: 'integer' },
  { key: 'pageView', title: '浏览量', format: 'integer' },
  { key: 'productFavoriteUserCount', title: '商品收藏人数', format: 'integer' },
  { key: 'cartUserCount', title: '加购人数', format: 'integer' },
  { key: 'orderBuyerCount', title: '下单买家数', format: 'integer' },
  { key: 'payBuyerCount', title: '支付买家数', format: 'integer' },
  { key: 'payQuantity', title: '支付件数', format: 'integer' },
  { key: 'payAmount', title: '支付金额', format: 'currency' },
  { key: 'payConversionRate', title: '支付转化率', format: 'rate' },
  { key: 'avgOrderValue', title: '客单价', format: 'currency' },
];

export const GOODS_CARD_TABLE_COLUMN_DEFINITIONS: GoodsCardColumnDefinition[] = [
  { key: 'shop_name', title: '店铺名称', format: 'text', width: 180 },
  { key: 'shop_id', title: '店铺ID', format: 'text', width: 150 },
  { key: 'product_id', title: '商品ID', format: 'text', width: 170 },
  { key: 'card_exposure_user_count', title: '商品卡曝光人数', format: 'integer', width: 154 },
  { key: 'card_click_user_count', title: '商品卡点击人数', format: 'integer', width: 154 },
  { key: 'card_click_rate_user', title: '商品卡点击率（人数）', format: 'rate', width: 172 },
  { key: 'card_click_count', title: '商品卡点击次数', format: 'integer', width: 154 },
  { key: 'card_avg_click_per_user', title: '人均点击次数', format: 'number', width: 144, digits: 2 },
  { key: 'new_customer_click_count', title: '新客点击次数', format: 'integer', width: 144 },
  { key: 'old_customer_click_count', title: '老客点击次数', format: 'integer', width: 144 },
  { key: 'new_customer_click_rate', title: '新客点击占比', format: 'rate', width: 144 },
  { key: 'old_customer_click_rate', title: '老客点击占比', format: 'rate', width: 144 },
  { key: 'card_user_pay_amount', title: '商品卡GMV', format: 'currency', width: 144 },
  { key: 'card_buyer_count', title: '商品卡成交人数', format: 'integer', width: 154 },
  { key: 'card_avg_order_value', title: '商品卡客单价', format: 'currency', width: 144 },
  { key: 'card_click_to_pay_rate_user', title: '点击-成交率（人数）', format: 'rate', width: 172 },
  { key: 'first_buy_user_count', title: '首购人数', format: 'integer', width: 118 },
  { key: 'rebuy_user_count', title: '复购人数', format: 'integer', width: 118 },
  { key: 'first_buy_new_rate', title: '首购新客占比', format: 'rate', width: 144 },
  { key: 'rebuy_old_rate', title: '复购老客占比', format: 'rate', width: 144 },
  { key: 'card_exposure_count', title: '商品卡曝光次数', format: 'integer', width: 154 },
  { key: 'card_exposure_to_pay_rate_user', title: '曝光-成交率（人数）', format: 'rate', width: 172 },
  { key: 'card_exposure_to_pay_rate_count', title: '曝光-成交率（次数）', format: 'rate', width: 172 },
  { key: 'card_gpm', title: '商品卡GPM', format: 'number', width: 128, digits: 2 },
  { key: 'card_click_rate_count', title: '点击率（次数）', format: 'rate', width: 144 },
  { key: 'card_click_to_pay_rate_count', title: '点击-成交率（次数）', format: 'rate', width: 172 },
  { key: 'card_cart_user_count', title: '商品卡加购人数', format: 'integer', width: 154 },
  { key: 'card_favorite_user_count', title: '商品卡收藏人数', format: 'integer', width: 154 },
  { key: 'card_order_count', title: '商品卡成交订单数', format: 'integer', width: 166 },
  { key: 'platform_support_exposure_count', title: '平台支持曝光次数', format: 'integer', width: 166 },
];

export const GOODS_CARD_TRAFFIC_METRIC_DEFINITIONS: GoodsCardTrafficMetricDefinition[] = [
  { key: 'cardExposureUserCount', title: '曝光人数', format: 'integer' },
  { key: 'cardClickUserCount', title: '点击人数', format: 'integer' },
  { key: 'cardClickRateUser', title: '点击率（人数）', format: 'rate' },
  { key: 'cardBuyerCount', title: '成交人数', format: 'integer' },
  { key: 'cardClickToPayRateUser', title: '点击-成交率（人数）', format: 'rate' },
  { key: 'cardExposureToPayRateUser', title: '曝光-成交率（人数）', format: 'rate' },
  { key: 'cardUserPayAmount', title: 'GMV', format: 'currency' },
  { key: 'cardOrderCount', title: '成交订单数', format: 'integer' },
  { key: 'cardCartUserCount', title: '加购人数', format: 'integer' },
  { key: 'cardFavoriteUserCount', title: '收藏人数', format: 'integer' },
  { key: 'cardBounceUserCount', title: '跳失人数', format: 'integer' },
];

export const LIVE_SCOPE_OPTIONS: Array<{ label: string; value: LiveScope }> = [
  { label: '全部', value: 'all' },
  { label: '自播', value: 'self' },
  { label: '达播', value: 'influencer' },
];

export const SHORT_VIDEO_SCOPE_OPTIONS: Array<{ label: string; value: ShortVideoScope }> = [
  { label: '全部', value: 'all' },
  { label: '自营', value: 'self' },
  { label: '合作', value: 'cooperation' },
];

export const LIVE_DETAIL_METRIC_DEFINITIONS: LiveDetailMetricDefinition[] = [
  { key: 'live_duration_minutes', title: '直播时长（分钟）', format: 'integer' },
  { key: 'live_exposure_user_count', title: '直播间曝光人数', format: 'integer' },
  { key: 'live_exposure_count', title: '直播间曝光次数', format: 'integer' },
  { key: 'live_watch_user_count', title: '直播间观看人数', format: 'integer' },
  { key: 'hourly_watch_user_count', title: '单小时观看人数', format: 'integer' },
  { key: 'live_watch_count', title: '直播间观看次数', format: 'integer' },
  { key: 'max_online_count', title: '最高在线人数', format: 'integer' },
  { key: 'avg_online_count', title: '平均在线人数', format: 'integer' },
  { key: 'avg_watch_duration_minutes', title: '人均观看时长（分钟）', format: 'number', digits: 2 },
  { key: 'comment_count', title: '评论次数', format: 'integer' },
  { key: 'new_live_group_count', title: '新加直播团人数', format: 'integer' },
  { key: 'new_follower_count', title: '新增粉丝数', format: 'integer' },
  { key: 'unfollow_count', title: '取关粉丝数', format: 'integer' },
  { key: 'old_follower_watch_rate', title: '观看老粉占比', format: 'rate' },
  { key: 'product_count', title: '带货商品数', format: 'integer' },
  { key: 'live_product_exposure_user', title: '直播间商品曝光人数', format: 'integer' },
  { key: 'live_product_click_user', title: '直播间商品点击人数', format: 'integer' },
  { key: 'live_product_exposure_count', title: '直播间商品曝光次数', format: 'integer' },
  { key: 'live_product_click_count', title: '直播间商品点击次数', format: 'integer' },
  { key: 'live_order_count', title: '直播间成交订单数', format: 'integer' },
  { key: 'live_gmv', title: '直播间成交金额', format: 'number', digits: 2 },
  { key: 'live_user_pay_amount', title: '直播间用户支付金额', format: 'number', digits: 2 },
  { key: 'hourly_user_pay_amount', title: '单小时用户支付金额', format: 'number', digits: 2 },
  { key: 'live_sale_quantity', title: '直播间成交件数', format: 'integer' },
  { key: 'live_buyer_count', title: '直播间成交人数', format: 'integer' },
  { key: 'live_refund_order_count', title: '直播间退款订单数', format: 'integer' },
  { key: 'live_refund_amount', title: '直播间退款金额', format: 'number', digits: 2 },
  { key: 'live_refund_user_count', title: '直播间退款人数', format: 'integer' },
  { key: 'estimated_commission', title: '预估佣金支出', format: 'number', digits: 2 },
  { key: 'product_click_rate_count', title: '商品曝光-点击率（次数）', format: 'rate' },
  { key: 'product_click_rate_user', title: '商品曝光-点击率（人数）', format: 'rate' },
  { key: 'click_to_pay_rate_count', title: '商品点击-成交率（次数）', format: 'rate' },
  { key: 'click_to_pay_rate_user', title: '商品点击-成交率（人数）', format: 'rate' },
  { key: 'watch_to_pay_rate_count', title: '观看-成交率（次数）', format: 'rate' },
  { key: 'watch_to_pay_rate_user', title: '观看-成交率（人数）', format: 'rate' },
  { key: 'presale_order_count', title: '预售订单数', format: 'integer' },
  { key: 'presale_full_amount', title: '预售全款金额', format: 'number', digits: 2 },
  { key: 'new_cart_group_count', title: '新加购物团人数', format: 'integer' },
  { key: 'live_ad_cost', title: '直播间投放消耗', format: 'number', digits: 2 },
  { key: 'net_gmv', title: '净成交金额', format: 'number', digits: 2 },
  { key: 'net_order_count', title: '净成交订单数', format: 'integer' },
  { key: 'refund_amount_1h', title: '1小时退款金额', format: 'number', digits: 2 },
  { key: 'refund_order_count_1h', title: '1小时退款订单数', format: 'integer' },
  { key: 'refund_rate_1h', title: '1小时退款率', format: 'rate' },
  { key: 'coupon_guided_payment_amount', title: '消费券引导支付金额', format: 'number', digits: 2 },
  { key: 'coupon_guided_payment_rate', title: '消费券引导支付占比', format: 'rate' },
  { key: 'coupon_subsidy_amount', title: '消费券补贴金额', format: 'number', digits: 2 },
  { key: 'coupon_usage_count', title: '消费券使用量', format: 'number', digits: 2 },
  { key: 'ad_cost_shop_bound', title: '直播投放消耗（店铺绑定）', format: 'number', digits: 2 },
  { key: 'ad_cost_shop_targeted', title: '直播投放消耗（店铺被投）', format: 'number', digits: 2 },
];

const LIVE_DETAIL_METRIC_DEFINITION_MAP = new Map<keyof DashboardLiveDetailRow, LiveDetailMetricDefinition>(
  LIVE_DETAIL_METRIC_DEFINITIONS.map((metric) => [metric.key, metric]),
);

function pickLiveDetailMetrics(keys: Array<keyof DashboardLiveDetailRow>): LiveDetailMetricDefinition[] {
  return keys
    .map((key) => LIVE_DETAIL_METRIC_DEFINITION_MAP.get(key))
    .filter((metric): metric is LiveDetailMetricDefinition => Boolean(metric));
}

export const LIVE_DETAIL_DRAWER_GROUPS: Array<{ title: string; metrics: LiveDetailMetricDefinition[] }> = [
  {
    title: '流量与互动',
    metrics: pickLiveDetailMetrics([
      'live_duration_minutes',
      'live_exposure_user_count',
      'live_exposure_count',
      'live_watch_user_count',
      'hourly_watch_user_count',
      'live_watch_count',
      'max_online_count',
      'avg_online_count',
      'avg_watch_duration_minutes',
      'comment_count',
      'new_live_group_count',
      'new_follower_count',
      'unfollow_count',
      'old_follower_watch_rate',
    ]),
  },
  {
    title: '商品与转化',
    metrics: pickLiveDetailMetrics([
      'product_count',
      'live_product_exposure_user',
      'live_product_click_user',
      'live_product_exposure_count',
      'live_product_click_count',
      'product_click_rate_count',
      'product_click_rate_user',
      'click_to_pay_rate_count',
      'click_to_pay_rate_user',
      'watch_to_pay_rate_count',
      'watch_to_pay_rate_user',
      'new_cart_group_count',
      'presale_order_count',
      'presale_full_amount',
    ]),
  },
  {
    title: '成交与退款',
    metrics: pickLiveDetailMetrics([
      'live_order_count',
      'live_gmv',
      'live_user_pay_amount',
      'hourly_user_pay_amount',
      'live_sale_quantity',
      'live_buyer_count',
      'net_gmv',
      'net_order_count',
      'live_refund_order_count',
      'live_refund_amount',
      'live_refund_user_count',
      'refund_amount_1h',
      'refund_order_count_1h',
      'refund_rate_1h',
      'estimated_commission',
    ]),
  },
  {
    title: '消费券与投放',
    metrics: pickLiveDetailMetrics([
      'coupon_guided_payment_amount',
      'coupon_guided_payment_rate',
      'coupon_subsidy_amount',
      'coupon_usage_count',
      'live_ad_cost',
      'ad_cost_shop_bound',
      'ad_cost_shop_targeted',
    ]),
  },
];
