import type { DataOpsPipeline } from './dataops-hub-types';

export const DATAOPS_REPORT_PIPELINES: DataOpsPipeline[] = [
  {
    id: 'ads_report_all_trade_week_platform_metrics_incremental',
    name: '周报平台扩展指标增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-report-all-trade-week-platform-metrics-flow',
    deploymentName: 'ads-report-04-platform-week-metrics-inc',
    cron: '32,57 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: [
      'ads.report_all_trade_week_platform',
      'ods.taobao_trade_sale_raw',
      'ods.taobao_one_alimama_marketingscenario',
    ],
    targetTables: ['ads.report_all_trade_week_platform_metrics'],
    procedures: ['ads.refresh_report_all_trade_week_platform_metrics_incremental(14, FALSE)'],
    watermarkTable: 'etl.report_all_trade_week_platform_metrics_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-02-28 14:35',
    lastSuccessAt: '2026-02-28 14:35',
    avgDurationSec: 74,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_report_all_trade_week_platform_metrics.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_report_all_trade_week_platform_metrics.sh',
    note: '补齐天猫平台核心指标（访客、支付转化率、UV价值、ROI）并与同期口径对齐。',
  },
  {
    id: 'ads_report_douyin_trade_sale_metrics_week_incremental',
    name: '周报抖音经营指标增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-report-douyin-trade-sale-metrics-week-flow',
    deploymentName: 'ads-report-05-douyin-week-metrics-inc',
    cron: '33,58 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: [
      'ads.report_all_trade_week_platform',
      'ods.douyin_trade_sale_raw',
    ],
    targetTables: ['ads.report_douyin_trade_sale_metrics_week'],
    procedures: ['ads.refresh_report_douyin_trade_sale_metrics_week_incremental(14, FALSE)'],
    watermarkTable: 'etl.report_douyin_trade_sale_metrics_week_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-03-03 19:32',
    lastSuccessAt: '2026-03-03 19:32',
    avgDurationSec: 86,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_report_douyin_trade_sale_metrics_week.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_report_douyin_trade_sale_metrics_week.sh',
    note: '沉淀 ods.douyin_trade_sale_raw 周指标（含金额/流量/转化/退款）并与 report_all_trade_week_platform 的同期窗口对齐。',
  },
  {
    id: 'ads_report_douyin_trade_sale_channel_metrics_week_incremental',
    name: '周报抖音渠道GMV指标增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-report-douyin-trade-sale-channel-metrics-week-flow',
    deploymentName: 'ads-report-06-douyin-week-channel-gmv-inc',
    cron: '35 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: [
      'ods.douyin_trade_sale_live_raw',
      'ods.douyin_trade_sale_shortvideo_raw',
      'ods.douyin_trade_sale_card_raw',
    ],
    targetTables: ['ads.report_douyin_trade_sale_channel_metrics_week'],
    procedures: ['ads.refresh_report_douyin_trade_sale_channel_metrics_week_incremental(14, FALSE)'],
    watermarkTable: 'etl.report_douyin_trade_sale_channel_metrics_week_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-03-03 16:35',
    lastSuccessAt: '2026-03-03 16:35',
    avgDurationSec: 79,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_report_douyin_trade_sale_channel_metrics_week.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_report_douyin_trade_sale_channel_metrics_week.sh',
    note: '用于周报抖音平台页直播/短视频/商品卡三渠道 GMV 指标，周口径与 report_all_trade_week_platform 同步。',
  },
  {
    id: 'ads_report_douyin_trade_sale_attribution_metrics_week_incremental',
    name: '周报抖音归因指标增量（直播/短视频/商品卡）',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-report-douyin-trade-sale-attribution-metrics-week-flow',
    deploymentName: 'ads-report-07-douyin-week-attribution-inc',
    cron: '37 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: [
      'ads.report_all_trade_week_platform',
      'ods.douyin_trade_sale_live_raw',
      'ods.douyin_trade_sale_shortvideo_raw',
      'ods.douyin_trade_sale_card_raw',
      'ods.douyin_trade_sale_card_detail_raw',
    ],
    targetTables: [
      'ads.report_douyin_trade_sale_live_metrics_week',
      'ads.report_douyin_trade_sale_shortvideo_metrics_week',
      'ads.report_douyin_trade_sale_card_metrics_week',
    ],
    procedures: [
      'ads.refresh_report_douyin_trade_sale_live_metrics_week_incremental(14, FALSE)',
      'ads.refresh_report_douyin_trade_sale_shortvideo_metrics_week_incremental(14, FALSE)',
      'ads.refresh_report_douyin_trade_sale_card_metrics_week_incremental(14, FALSE)',
    ],
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-03-05 18:37',
    lastSuccessAt: '2026-03-05 18:37',
    avgDurationSec: 102,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_report_douyin_trade_sale_attribution_metrics_week.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_report_douyin_trade_sale_attribution_metrics_week.sh',
    note: '用于周报抖音归因明细模块：直播场次定位、短视频内容定位、商品卡商品/来源定位。',
  },
  {
    id: 'ads_report_taobao_trade_product_metrics_week_incremental',
    name: '周报天猫商品归因指标增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-report-taobao-trade-product-metrics-week-flow',
    deploymentName: 'ads-report-08-taobao-week-product-attribution-inc',
    cron: '40 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: [
      'ads.report_all_trade_week_platform',
      'ods.taobao_trade_sale_goods_raw',
    ],
    targetTables: ['ads.report_taobao_trade_product_metrics_week'],
    procedures: ['ads.refresh_report_taobao_trade_product_metrics_week_incremental(14, FALSE)'],
    watermarkTable: 'etl.report_taobao_trade_product_metrics_week_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-02-28 14:40',
    lastSuccessAt: '2026-02-28 14:40',
    avgDurationSec: 88,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_report_taobao_trade_product_metrics_week.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_report_taobao_trade_product_metrics_week.sh',
    note: '用于周报天猫页商品归因（商品列表 + 商品GMV增量瀑布）。',
  },
  {
    id: 'ads_report_taobao_goods_traffic_channel_metrics_week_incremental',
    name: '周报天猫商品流量渠道归因指标增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-report-taobao-goods-traffic-channel-metrics-week-flow',
    deploymentName: 'ads-report-09-taobao-week-traffic-channel-attribution-inc',
    cron: '45 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: [
      'ads.report_all_trade_week_platform',
      'dwd.taobao_goods_sale_traffic',
    ],
    targetTables: ['ads.report_taobao_goods_traffic_channel_metrics_week'],
    procedures: ['ads.refresh_report_taobao_goods_traffic_channel_metrics_week_incremental(14, FALSE)'],
    watermarkTable: 'etl.report_taobao_goods_traffic_channel_metrics_week_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-02-28 14:45',
    lastSuccessAt: '2026-02-28 14:45',
    avgDurationSec: 93,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_report_taobao_goods_traffic_channel_metrics_week.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_report_taobao_goods_traffic_channel_metrics_week.sh',
    note: '用于周报天猫页商品流量渠道定位（渠道明细 + 渠道GMV增量瀑布）。',
  },
  {
    id: 'ads_report_taobao_one_goods_traffic_channel_metric_week_incremental',
    name: '周报淘宝万相台商品流量渠道漏斗指标增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-report-taobao-one-goods-traffic-channel-metric-week-flow',
    deploymentName: 'ads-report-10-taobao-one-week-traffic-funnel-inc',
    cron: '48 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: [
      'ads.report_all_trade_week_platform',
      'ods.taobao_one_alimama_goods_marketingscenario',
    ],
    targetTables: ['ads.report_taobao_one_goods_traffic_channel_metric_week'],
    procedures: ['ads.refresh_report_taobao_one_goods_traffic_channel_metric_week_incremental(14, FALSE)'],
    watermarkTable: 'etl.report_taobao_one_goods_traffic_channel_metric_week_refresh_state',
    owner: '营销数据组',
    status: 'healthy',
    lastRunAt: '2026-03-02 18:48',
    lastSuccessAt: '2026-03-02 18:48',
    avgDurationSec: 102,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_report_taobao_one_goods_traffic_channel_metric_week.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_report_taobao_one_goods_traffic_channel_metric_week.sh',
    note: '用于周报淘宝页“流量漏斗 + 量化归因”模块（关键词推广/搜索等付费渠道）。',
  },
];
