import type { DataOpsPipeline } from './dataops-hub-types';

export const DATAOPS_DASHBOARD_PIPELINES: DataOpsPipeline[] = [
  {
    id: 'dwd_taobao_goods_sale_traffic_daily',
    name: '淘宝商品流量成交日刷',
    domain: 'DWD',
    flowName: 'refresh-dwd-taobao-goods-sale-traffic-flow',
    deploymentName: 'dwd-04-taobao-goods-sale-traffic-daily',
    cron: '40 2 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 7,
    sourceTables: ['ods.taobao_trade_sale_goods_raw'],
    targetTables: ['dwd.taobao_goods_sale_traffic'],
    procedures: ['dwd.refresh_taobao_goods_sale_traffic(start_date, end_date)'],
    owner: '电商数据组',
    status: 'healthy',
    lastRunAt: '2026-03-12 02:40',
    lastSuccessAt: '2026-03-12 02:40',
    avgDurationSec: 189,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_refresh_taobao_goods_sale_traffic.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_refresh_taobao_goods_sale_traffic.sh',
    note: '为 ADS 天猫商品流量渠道归因提供 DWD 上游底表。',
  },
  {
    id: 'ads_all_trade_overview_incremental',
    name: '全渠道日汇总总览增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-all-trade-overview-flow',
    deploymentName: 'ads-01-overview-daily-inc',
    cron: '30,55 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 7,
    sourceTables: [
      'ods.douyin_trade_sale_raw',
      'ods.jd_trade_sale_raw',
      'ods.taobao_trade_sale_raw',
      'ods.wx_trade_sale_raw',
      'ods.xhs_trade_sale_raw',
    ],
    targetTables: ['ads.all_trade_overview', 'ads.douyin_trade_sale_carrier_daily'],
    procedures: ['ads.refresh_all_trade_overview_incremental(7, FALSE)'],
    watermarkTable: 'etl.all_trade_overview_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-03-03 23:00',
    lastSuccessAt: '2026-03-03 23:00',
    avgDurationSec: 58,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_all_trade_overview.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_all_trade_overview.sh',
    note: '看板日级核心指标底座（10/18 点各一次主刷 + catch-up），包含抖音载体成交金额、退款金额（支付时间）nowcast 与 WAPE 质量告警（阈值 0.15）。',
  },
  {
    id: 'ads_all_trade_overview_refund_nowcast_weekly_calibration',
    name: '全渠道总览退款 nowcast 周度校准',
    domain: 'ADS',
    flowName: 'weekly-overview-refund-nowcast-calibration-flow',
    deploymentName: 'ads-01-overview-refund-nowcast-weekly-calibration',
    cron: '15 9 * * 1',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 42,
    sourceTables: ['ads.all_trade_overview_refund_nowcast_daily'],
    targetTables: [
      'ads.all_trade_overview_refund_nowcast_calibration_weekly',
      'ads.all_trade_overview_refund_nowcast_active_calibration',
    ],
    procedures: [
      'ads.refresh_all_trade_overview_refund_nowcast_calibration_weekly(CURRENT_DATE, 42, 10, 0.15)',
      'ads.activate_all_trade_overview_refund_nowcast_calibration(CURRENT_DATE, 42, 10, 0.08)',
    ],
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '待部署',
    lastSuccessAt: '待部署',
    avgDurationSec: 30,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_weekly_overview_refund_nowcast_calibration.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_weekly_overview_refund_nowcast_calibration.sh',
    note: '每周评估退款 nowcast 的 WAPE/bias/zero-miss，通过护栏后激活 active calibration 参数；日常预测由 ads-01-overview-daily-inc 读取生效参数。',
  },
  {
    id: 'ads_taobao_trade_sale_goods_daily_incremental',
    name: '天猫商品成交日粒度看板增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-taobao-trade-sale-goods-daily-flow',
    deploymentName: 'ads-15-taobao-goods-daily-inc',
    cron: '22,52 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: ['ods.taobao_trade_sale_goods_raw'],
    targetTables: ['ads.taobao_trade_sale_goods_daily'],
    procedures: ['ads.refresh_taobao_trade_sale_goods_daily_incremental(14, FALSE)'],
    watermarkTable: 'etl.taobao_trade_sale_goods_daily_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-03-17 18:22',
    lastSuccessAt: '2026-03-17 18:22',
    avgDurationSec: 46,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_taobao_trade_sale_goods_daily.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_taobao_trade_sale_goods_daily.sh',
    note: '用于经营看板天猫商品维度（日/周/月/年/自定义）查询底表增量刷新。',
  },
  {
    id: 'ads_taobao_traffic_shop_daily_incremental',
    name: '天猫店铺流量日粒度看板增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-taobao-traffic-shop-daily-flow',
    deploymentName: 'ads-16-taobao-traffic-shop-daily-inc',
    cron: '24,54 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: ['ods.taobao_traffic_shop_raw'],
    targetTables: ['ads.taobao_traffic_shop_daily'],
    procedures: ['ads.refresh_taobao_traffic_shop_daily_incremental(14, FALSE)'],
    watermarkTable: 'etl.taobao_traffic_shop_daily_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-04-09 18:24',
    lastSuccessAt: '2026-04-09 18:24',
    avgDurationSec: 44,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_taobao_traffic_shop_daily.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_taobao_traffic_shop_daily.sh',
    note: '用于经营看板天猫-流量维度来源层级（日/周/月/年/自定义）查询底表增量刷新。',
  },
  {
    id: 'ads_taobao_traffic_goods_daily_incremental',
    name: '天猫商品流量日粒度看板增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-taobao-traffic-goods-daily-flow',
    deploymentName: 'ads-17-taobao-traffic-goods-daily-inc',
    cron: '26,56 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: ['ods.taobao_traffic_goods_raw', 'ods.taobao_trade_sale_goods_raw'],
    targetTables: ['ads.taobao_traffic_goods_daily'],
    procedures: ['ads.refresh_taobao_traffic_goods_daily_incremental(14, FALSE)'],
    watermarkTable: 'etl.taobao_traffic_goods_daily_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-04-09 18:26',
    lastSuccessAt: '2026-04-09 18:26',
    avgDurationSec: 48,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_taobao_traffic_goods_daily.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_taobao_traffic_goods_daily.sh',
    note: '用于经营看板天猫-商品流量来源层级（日/周/月/年/自定义）查询底表增量刷新。',
  },
  {
    id: 'ads_douyin_live_detail_incremental',
    name: '抖音直播明细看板增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-douyin-live-detail-flow',
    deploymentName: 'ads-18-douyin-live-detail-inc',
    cron: '36,56 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: ['ods.douyin_trade_sale_live_raw', 'ads.douyin_self_anchor_map'],
    targetTables: ['ads.douyin_live_detail'],
    procedures: ['ads.refresh_douyin_live_detail_incremental(14, FALSE)'],
    watermarkTable: 'etl.douyin_live_detail_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-04-22 18:36',
    lastSuccessAt: '2026-04-22 18:36',
    avgDurationSec: 41,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_douyin_live_detail.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_douyin_live_detail.sh',
    note: '支撑 /dashboard 抖音直播维度：顶部指标卡、趋势、以及直播场次明细。',
  },
  {
    id: 'ads_douyin_live_goods_detail_incremental',
    name: '抖音直播商品明细看板增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-douyin-live-goods-detail-flow',
    deploymentName: 'ads-20-douyin-live-goods-detail-inc',
    cron: '38,58 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: [
      'ods.douyin_livestream_goods',
      'ads.douyin_live_detail',
      'ads.douyin_self_anchor_map',
    ],
    targetTables: ['ads.douyin_live_goods_detail'],
    procedures: ['ads.refresh_douyin_live_goods_detail_incremental(14, FALSE)'],
    watermarkTable: 'etl.douyin_live_goods_detail_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-04-27 18:38',
    lastSuccessAt: '2026-04-27 18:38',
    avgDurationSec: 43,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_douyin_live_goods_detail.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_douyin_live_goods_detail.sh',
    note: '支撑 /dashboard 抖音直播维度下方的直播商品表现树表（商品汇总+SKU展开）。',
  },
  {
    id: 'ads_douyin_trade_sale_card_dashboard_incremental',
    name: '抖音商品卡看板增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-douyin-trade-sale-card-dashboard-flow',
    deploymentName: 'ads-21-douyin-trade-sale-card-dashboard-inc',
    cron: '39,59 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: ['ods.douyin_trade_sale_card_raw', 'ods.douyin_trade_sale_card_detail_raw'],
    targetTables: ['ads.douyin_trade_sale_card', 'ads.douyin_trade_sale_card_detail'],
    procedures: ['ads.refresh_douyin_trade_sale_card_dashboard_incremental(14, FALSE)'],
    watermarkTable: 'etl.douyin_trade_sale_card_dashboard_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '待部署',
    lastSuccessAt: '待部署',
    avgDurationSec: 38,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_douyin_trade_sale_card_dashboard.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_douyin_trade_sale_card_dashboard.sh',
    note: '支撑 /dashboard 抖音商品卡维度：指标卡、GMV/曝光趋势、商品卡全字段列表与流量来源层级明细。',
  },
  {
    id: 'ads_douyin_shortvideo_detail_incremental',
    name: '抖音短视频明细看板增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-douyin-shortvideo-detail-flow',
    deploymentName: 'ads-19-douyin-shortvideo-detail-inc',
    cron: '37,57 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: [
      'ods.douyin_trade_sale_shortvideo_raw',
      'ods.douyin_trade_sale_image_raw',
      'ods.douyin_qianchuan_shortvideo_raw',
      'ads.marketing_content_platform_videos',
      'ads.marketing_content_ad_materials',
      'ads.marketing_content_assets',
    ],
    targetTables: ['ads.douyin_shortvideo_detail'],
    procedures: ['ads.refresh_douyin_shortvideo_detail_incremental(14, FALSE)'],
    watermarkTable: 'etl.douyin_shortvideo_detail_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-04-24 18:37',
    lastSuccessAt: '2026-04-24 18:37',
    avgDurationSec: 39,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_douyin_shortvideo_detail.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_douyin_shortvideo_detail.sh',
    note:
      '支撑 /dashboard 抖音短视频维度与达人短视频页：成交侧合并短视频与图文短视频 ODS，千川素材映射指标避免多 account_type 分层重复广告成本。',
  },
  {
    id: 'dws_marketing_content_qianchuan_all_domain_material_performance',
    name: '内容素材千川全域素材表现刷新',
    domain: 'DWS',
    flowName: 'refresh-marketing-content-qianchuan-all-domain-material-performance',
    deploymentName: 'manual-marketing-content-qianchuan-all-domain-material-performance',
    cron: 'manual',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 30,
    sourceTables: [
      'ods.douyin_qianchuan_shortvideo_raw',
      'ods.douyin_qianchuan_live_video_raw',
      'ods.douyin_trade_sale_live_raw',
      'ads.marketing_content_platform_videos',
      'ads.marketing_content_ad_materials',
      'ads.marketing_content_assets',
    ],
    targetTables: [
      'dwd.marketing_content_qianchuan_material_performance_di',
      'dws.marketing_content_qianchuan_material_summary',
      'dws.marketing_content_qianchuan_live_room_acceptance_di',
    ],
    procedures: [
      'ads.refresh_marketing_content_qianchuan_all_domain_performance(asset_id, start_date, end_date)',
    ],
    watermarkTable: 'dwd.marketing_content_qianchuan_material_performance_di.updated_at',
    owner: '数据平台组',
    status: 'warning',
    lastRunAt: '待部署',
    lastSuccessAt: '待部署',
    avgDurationSec: 45,
    linuxDeployScript: 'etl/groland_postgres/scripts/refresh_qianchuan_all_domain_material_performance.py',
    linuxDeployCommand:
      'python3 etl/groland_postgres/scripts/refresh_qianchuan_all_domain_material_performance.py --days 30',
    note:
      '内容中台 /marketing/content-assets 投放快照和 daily trend 的数据底座；material_id 是千川素材实例唯一键，boost_* 只作解释项。',
  },
  {
    id: 'ads_marketing_content_asset_fusion_diagnostics',
    name: '内容素材视频理解与融合诊断',
    domain: 'ADS',
    flowName: 'process-marketing-content-asset-analysis-jobs',
    deploymentName: 'marketing-content-asset-analysis-jobs',
    cron: '3-59/10 * * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 7,
    sourceTables: [
      'ads.marketing_content_asset_processing_jobs',
      'ads.marketing_content_asset_objects',
      'ads.marketing_content_asset_transcripts',
      'ads.marketing_content_asset_video_understanding_results',
      'dws.marketing_content_qianchuan_material_summary',
    ],
    targetTables: [
      'ads.marketing_content_asset_video_understanding_jobs',
      'ads.marketing_content_asset_video_understanding_results',
      'ads.marketing_content_asset_objects(object_role=analysis)',
    ],
    procedures: ['process_content_asset_analysis_jobs(limit, temp_dir)'],
    watermarkTable: 'ads.marketing_content_asset_processing_jobs.updated_at',
    owner: '内容中台',
    status: 'warning',
    lastRunAt: '待部署',
    lastSuccessAt: '待部署',
    avgDurationSec: 55,
    linuxDeployScript: 'etl/groland_postgres/scripts/deploy_prefect_process_marketing_content_asset_analysis_jobs.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_process_marketing_content_asset_analysis_jobs.sh',
    note:
      '生成 v2.1 视频理解 + 数据表现融合诊断；缺 performance/video 任一侧时输出 degraded mode，不做单边过度结论。',
  },
  {
    id: 'ads_marketing_industry_articles_incremental',
    name: '行业公众号文章发现与正文补全',
    domain: 'ADS',
    flowName: 'sync-marketing-industry-articles-flow',
    deploymentName: 'ads-21-marketing-industry-articles-inc',
    cron: '17 8-22/2 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 45,
    sourceTables: [
      'ads.marketing_industry_article_sources',
      'WeChat RSS API',
    ],
    targetTables: [
      'ads.marketing_industry_articles',
      'etl.marketing_industry_article_sync_state',
      'etl.marketing_industry_article_upstream_status',
    ],
    procedures: [
      'sync_marketing_industry_articles_flow(sync_article_lists=true, backfill_missing_content=true)',
    ],
    watermarkTable: 'etl.marketing_industry_article_sync_state.updated_at',
    owner: '内容中台',
    status: 'warning',
    lastRunAt: '待运行',
    lastSuccessAt: '待运行',
    avgDurationSec: 180,
    linuxDeployScript: 'etl/groland_postgres/scripts/deploy_prefect_marketing_industry_articles.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_marketing_industry_articles.sh',
    note: '发现行业公众号新文章并补全正文；DataOps 手动触发使用 Deployment 已固化的安全参数。',
  },
  {
    id: 'ads_marketing_industry_articles_cache_sweep',
    name: '行业公众号文章缓存补扫',
    domain: 'ADS',
    flowName: 'sync-marketing-industry-articles-flow',
    deploymentName: 'ads-21-marketing-industry-articles-cache-sweep',
    cron: '7 * * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 45,
    sourceTables: [
      'ads.marketing_industry_articles',
      'WeChat RSS cache',
    ],
    targetTables: [
      'ads.marketing_industry_articles',
      'etl.marketing_industry_article_sync_state',
    ],
    procedures: [
      'sync_marketing_industry_articles_flow(sync_article_lists=false, cache_only_backfill=true)',
    ],
    watermarkTable: 'ads.marketing_industry_articles.last_content_fetched_at',
    owner: '内容中台',
    status: 'warning',
    lastRunAt: '待运行',
    lastSuccessAt: '待运行',
    avgDurationSec: 240,
    linuxDeployScript: 'etl/groland_postgres/scripts/deploy_prefect_marketing_industry_articles.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_marketing_industry_articles.sh',
    note: '仅使用本地 RSS 缓存补扫缺失正文；不重新拉取文章列表或外部正文。',
  },
  {
    id: 'ads_marketing_industry_articles_content_retry',
    name: '行业公众号文章正文失败重试',
    domain: 'ADS',
    flowName: 'sync-marketing-industry-articles-flow',
    deploymentName: 'ads-21-marketing-industry-articles-content-retry',
    cron: '43 */6 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 45,
    sourceTables: [
      'ads.marketing_industry_articles',
      'WeChat RSS API',
    ],
    targetTables: [
      'ads.marketing_industry_articles',
      'etl.marketing_industry_article_sync_state',
      'etl.marketing_industry_article_upstream_status',
    ],
    procedures: [
      'sync_marketing_industry_articles_flow(sync_article_lists=false, backfill_missing_content=true)',
    ],
    watermarkTable: 'ads.marketing_industry_articles.last_content_fetched_at',
    owner: '内容中台',
    status: 'warning',
    lastRunAt: '待运行',
    lastSuccessAt: '待运行',
    avgDurationSec: 240,
    linuxDeployScript: 'etl/groland_postgres/scripts/deploy_prefect_marketing_industry_articles.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_marketing_industry_articles.sh',
    note: '重试尚未补全的文章正文；DataOps API 保留认证、活动运行锁和审计。',
  },
  {
    id: 'ads_creator_live_dashboard_incremental',
    name: '直播达人看板增量',
    domain: 'ADS',
    flowName: 'incremental-refresh-ads-creator-live-dashboard-flow',
    deploymentName: 'ads-13-creator-live-dashboard-inc',
    cron: '33 10,18 * * *',
    timezone: 'Asia/Shanghai',
    fallbackWindowDays: 14,
    sourceTables: [
      'ods.feishu_influencer_live',
      'ods.douyin_trade_sale_live_raw',
    ],
    targetTables: [
      'ads.influencer_live_roster',
      'ads.influencer_live_detail',
    ],
    procedures: ['ads.refresh_creator_live_dashboard_incremental(14, FALSE)'],
    watermarkTable: 'etl.creator_live_dashboard_refresh_state',
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-03-31 10:33',
    lastSuccessAt: '2026-03-31 10:33',
    avgDurationSec: 42,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_incremental_creator_live_dashboard.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_incremental_creator_live_dashboard.sh',
    note: '用于带货达人看板直播页：名册快照 + 直播日事实双底表增量刷新。',
  },
];
