import type { DataOpsPipeline } from './dataops-hub-types';

export const DATAOPS_OPS_PIPELINES: DataOpsPipeline[] = [
  {
    id: 'dashboard_ads_freshness_check',
    name: 'Dashboard ADS 新鲜度检查',
    domain: 'OPS',
    flowName: 'dashboard-ads-freshness-check-flow',
    deploymentName: 'dashboard-ads-freshness-check',
    cron: '45 10,18 * * *',
    timezone: 'Asia/Shanghai',
    sourceTables: [
      'ods.*_trade_sale_raw',
      'ods.taobao_trade_sale_goods_raw',
      'ods.taobao_traffic_shop_raw',
      'ods.taobao_traffic_goods_raw',
      'ods.douyin_trade_sale_live_raw',
      'ods.douyin_livestream_goods',
      'ods.douyin_trade_sale_shortvideo_raw',
      'ods.douyin_trade_sale_image_raw',
      'ods.douyin_trade_sale_card_raw',
      'ods.douyin_trade_sale_card_detail_raw',
    ],
    targetTables: [
      'ads.all_trade_overview',
      'ads.taobao_trade_sale_goods_daily',
      'ads.taobao_traffic_shop_daily',
      'ads.taobao_traffic_goods_daily',
      'ads.douyin_live_detail',
      'ads.douyin_live_goods_detail',
      'ads.douyin_shortvideo_detail',
      'ads.douyin_trade_sale_card',
      'ads.douyin_trade_sale_card_detail',
    ],
    procedures: ['dashboard_ads_freshness_check_flow(target_date, notify_on_issue_only, fail_on_stale)'],
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '待部署',
    lastSuccessAt: '待部署',
    avgDurationSec: 8,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_dashboard_ads_freshness_check.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_dashboard_ads_freshness_check.sh',
    note: '只读对比昨日 ODS/ADS 行数，区分 ODS 未到、ADS 未刷和已新鲜，默认仅异常通知。',
  },
  {
    id: 'dataops_runtime_events_cleanup',
    name: 'DataOps 运行态事件定时清理',
    domain: 'OPS',
    flowName: 'cleanup-dataops-runtime-events-flow',
    deploymentName: 'cleanup-dataops-runtime-events-daily',
    cron: '15 3 * * *',
    timezone: 'Asia/Shanghai',
    sourceTables: [
      'dataops.runtime_audit_events',
      'dataops.runtime_notification_events',
      'dataops.runtime_batch_execution_events',
    ],
    targetTables: [
      'dataops.runtime_audit_events',
      'dataops.runtime_notification_events',
      'dataops.runtime_batch_execution_events',
      'dataops.runtime_cleanup_state',
    ],
    procedures: [
      'SELECT * FROM dataops.cleanup_runtime_events(retain_days, cleanup_batch_execution_events)',
    ],
    owner: '平台运维组',
    status: 'healthy',
    lastRunAt: '2026-02-28 03:15',
    lastSuccessAt: '2026-02-28 03:15',
    avgDurationSec: 9,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_cleanup_dataops_runtime_events.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_cleanup_dataops_runtime_events.sh',
    note: '每天按保留策略清理运行态事件（含批量历史，可按参数关闭），并记录最近清理结果供 DataOps 页面观测。',
  },
  {
    id: 'dataops_notification_trace_slo_scan',
    name: 'DataOps 通知链路 SLO 巡检',
    domain: 'OPS',
    flowName: 'dataops-notification-trace-slo-scan-flow',
    deploymentName: 'dataops-notification-trace-slo-scan',
    cron: '*/15 * * * *',
    timezone: 'Asia/Shanghai',
    sourceTables: ['dataops.runtime_notification_events'],
    targetTables: ['dataops.runtime_notification_events'],
    procedures: ['POST /v1/dataops/runtime/notification-trace/scan'],
    owner: '平台运维组',
    status: 'healthy',
    lastRunAt: '2026-03-02 18:45',
    lastSuccessAt: '2026-03-02 18:45',
    avgDurationSec: 6,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_dataops_notification_trace_slo_scan.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_dataops_notification_trace_slo_scan.sh',
    note: '周期扫描通知失败重试组，识别 SLO 风险并按策略发送飞书提醒。',
  },
  {
    id: 'daily_business_brief',
    name: '每日生意简报',
    domain: 'OPS',
    flowName: 'daily-business-brief-flow',
    deploymentName: 'daily-business-brief',
    cron: 'event:ads-overview-ready',
    timezone: 'Asia/Shanghai',
    sourceTables: [
      'ads.all_trade_overview',
      'ods.douyin_trade_sale_raw',
      'ods.taobao_trade_sale_raw',
      'ods.wx_trade_sale_raw',
      'ods.xhs_trade_sale_raw',
      'ods.jd_trade_sale_raw',
    ],
    targetTables: ['dataops.daily_business_brief_deliveries'],
    procedures: [
      'daily_business_brief_flow(target_date, delivery_mode, production_confirmed)',
    ],
    owner: '数据平台组',
    status: 'healthy',
    lastRunAt: '2026-08-25 14:51',
    lastSuccessAt: '2026-08-25 14:51',
    avgDurationSec: 12,
    linuxDeployScript:
      'etl/groland_postgres/scripts/deploy_prefect_daily_business_brief.sh',
    linuxDeployCommand:
      'bash etl/groland_postgres/scripts/deploy_prefect_daily_business_brief.sh',
    batchTriggerAllowed: false,
    note: 'ADS 五平台目标日总览就绪后自动请求正式简报；手工正式补发仍需单独选择 production 并显式确认。',
  },
];
