/**
 * DataOps Hub 配置
 *
 * 数据来源：
 * - etl/groland_postgres/scripts/*.py
 * - etl/groland_postgres/scripts/deploy_prefect_*.sh
 *
 * 说明：
 * 1. 结构化静态配置用于描述 ETL 链路，避免运维信息散落在脚本内
 * 2. 运行时页面优先使用后端 DataOps Runtime 接口，接口无数据时回退到这份静态配置
 */

import type { DataSyncStream } from './dataops-hub-types';

export const DATA_SYNC_STREAMS: DataSyncStream[] = [
  {
    id: 'stream_trade_overview',
    streamName: '日经营总览链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.*_trade_sale_raw',
    target: 'ads.all_trade_overview / ads.douyin_trade_sale_carrier_daily',
    checkpointTable: 'etl.all_trade_overview_refresh_state',
    lagMinutes: 19,
    lastSyncAt: '2026-03-03 23:00',
    status: 'healthy',
    note: '支撑 Dashboard 日/周/月、自定义区间真实经营数据，以及抖音生意载体成交金额卡片。',
  },
  {
    id: 'stream_taobao_trade_sale_goods_daily',
    streamName: '天猫商品成交日粒度看板链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.taobao_trade_sale_goods_raw',
    target: 'ads.taobao_trade_sale_goods_daily',
    checkpointTable: 'etl.taobao_trade_sale_goods_daily_refresh_state',
    lagMinutes: 27,
    lastSyncAt: '2026-03-17 18:22',
    status: 'healthy',
    note: '支撑经营看板天猫商品维度（商品成交、退款、支付人数与商品明细）日级事实底表。',
  },
  {
    id: 'stream_taobao_traffic_shop_daily',
    streamName: '天猫店铺流量日粒度看板链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.taobao_traffic_shop_raw',
    target: 'ads.taobao_traffic_shop_daily',
    checkpointTable: 'etl.taobao_traffic_shop_daily_refresh_state',
    lagMinutes: 26,
    lastSyncAt: '2026-04-09 18:24',
    status: 'healthy',
    note: '支撑经营看板天猫流量维度（来源树、转化指标、较上周期）日级事实底表。',
  },
  {
    id: 'stream_taobao_traffic_goods_daily',
    streamName: '天猫商品流量日粒度看板链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.taobao_traffic_goods_raw / ods.taobao_trade_sale_goods_raw',
    target: 'ads.taobao_traffic_goods_daily',
    checkpointTable: 'etl.taobao_traffic_goods_daily_refresh_state',
    lagMinutes: 28,
    lastSyncAt: '2026-04-09 18:26',
    status: 'healthy',
    note: '支撑经营看板天猫流量维度商品来源树（商品+来源层级、较上周期）日级事实底表。',
  },
  {
    id: 'stream_douyin_live_detail',
    streamName: '抖音直播明细看板链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.douyin_trade_sale_live_raw / ads.douyin_self_anchor_map',
    target: 'ads.douyin_live_detail',
    checkpointTable: 'etl.douyin_live_detail_refresh_state',
    lagMinutes: 24,
    lastSyncAt: '2026-04-22 18:36',
    status: 'healthy',
    note: '支撑 /dashboard 抖音直播维度（总览+自播+达播）的场次明细事实。',
  },
  {
    id: 'stream_douyin_live_goods_detail',
    streamName: '抖音直播商品明细看板链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.douyin_livestream_goods / ads.douyin_live_detail / ads.douyin_self_anchor_map',
    target: 'ads.douyin_live_goods_detail',
    checkpointTable: 'etl.douyin_live_goods_detail_refresh_state',
    lagMinutes: 25,
    lastSyncAt: '2026-04-27 18:38',
    status: 'healthy',
    note: '支撑经营看板抖音直播商品表现（商品汇总行与 SKU 子行）。',
  },
  {
    id: 'stream_douyin_trade_sale_card_dashboard',
    streamName: '抖音商品卡看板链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.douyin_trade_sale_card_raw / ods.douyin_trade_sale_card_detail_raw',
    target: 'ads.douyin_trade_sale_card / ads.douyin_trade_sale_card_detail',
    checkpointTable: 'etl.douyin_trade_sale_card_dashboard_refresh_state',
    lagMinutes: 26,
    lastSyncAt: '待部署',
    status: 'healthy',
    note: '支撑经营看板抖音商品卡维度（商品卡主表与流量来源层级明细）。',
  },
  {
    id: 'stream_douyin_shortvideo_detail',
    streamName: '抖音短视频明细看板链路',
    layers: ['ODS', 'ADS'],
    source:
      'ods.douyin_trade_sale_shortvideo_raw / ods.douyin_trade_sale_image_raw / ods.douyin_qianchuan_shortvideo_raw / ads.marketing_content_platform_videos / ads.marketing_content_ad_materials / ads.marketing_content_assets',
    target: 'ads.douyin_shortvideo_detail',
    checkpointTable: 'etl.douyin_shortvideo_detail_refresh_state',
    lagMinutes: 25,
    lastSyncAt: '2026-04-24 18:37',
    status: 'healthy',
    note:
      '支撑 /dashboard 抖音短视频维度与达人短视频页：成交侧合并短视频与图文短视频 ODS + 千川素材映射指标 + 素材库分类字段。',
  },
  {
    id: 'stream_marketing_content_qianchuan_all_domain_material_performance',
    streamName: '内容素材千川全域素材表现链路',
    layers: ['ODS', 'DWD', 'DWS'],
    source:
      'ods.douyin_qianchuan_shortvideo_raw / ods.douyin_qianchuan_live_video_raw / ods.douyin_trade_sale_live_raw / ads.marketing_content_platform_videos / ads.marketing_content_ad_materials',
    target:
      'dwd.marketing_content_qianchuan_material_performance_di / dws.marketing_content_qianchuan_material_summary / dws.marketing_content_qianchuan_live_room_acceptance_di',
    checkpointTable: 'dwd.marketing_content_qianchuan_material_performance_di.updated_at',
    lagMinutes: 35,
    lastSyncAt: '待部署',
    status: 'warning',
    note:
      '支撑内容中台投放快照和 performance/daily：按千川 material_id 回填全域素材表现；直播成交原始表仅作为账号日期承接环境，不做单素材精确归因。',
  },
  {
    id: 'stream_marketing_content_asset_video_understanding',
    streamName: '内容素材视频理解链路',
    layers: ['ADS', 'AI'],
    source:
      'ads.marketing_content_assets / ads.marketing_content_asset_objects / ads.marketing_content_asset_transcripts / ads.marketing_content_asset_processing_jobs',
    target:
      'ads.marketing_content_asset_video_understanding_jobs / ads.marketing_content_asset_video_understanding_results',
    checkpointTable: 'ads.marketing_content_asset_video_understanding_jobs.updated_at',
    lagMinutes: 10,
    lastSyncAt: '待部署',
    status: 'warning',
    note:
      '沉淀 media_hash、model、prompt_version、analysis_schema_version、input_snapshot_hash 与 cache_key，避免重复视频理解模型调用。',
  },
  {
    id: 'stream_marketing_content_asset_fusion_diagnostics',
    streamName: '内容素材数据内容融合诊断链路',
    layers: ['DWS', 'AI', 'ADS'],
    source:
      'dws.marketing_content_qianchuan_material_summary / ads.marketing_content_asset_video_understanding_results / ads.marketing_content_asset_transcripts',
    target: 'ads.marketing_content_asset_objects(object_role=analysis)',
    checkpointTable: 'ads.marketing_content_asset_processing_jobs.updated_at',
    lagMinutes: 12,
    lastSyncAt: '待部署',
    status: 'warning',
    note:
      '生成 v2.1 融合诊断、证据账本和 next_actions；缺 performance 或 video understanding 时必须显式降级。',
  },
  {
    id: 'stream_creator_live_dashboard',
    streamName: '直播达人看板链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.feishu_influencer_live / ods.douyin_trade_sale_live_raw',
    target: 'ads.influencer_live_roster / ads.influencer_live_detail',
    checkpointTable: 'etl.creator_live_dashboard_refresh_state',
    lagMinutes: 21,
    lastSyncAt: '2026-03-31 10:33',
    status: 'healthy',
    note: '支撑 /dashboard/creator/live 的名册分组、趋势与导出明细。',
  },
  {
    id: 'stream_creator_shortvideo_dashboard',
    streamName: '短视频达人看板链路',
    layers: ['ODS', 'ADS'],
    source: 'ads.douyin_shortvideo_detail',
    target: 'ads.douyin_shortvideo_detail',
    checkpointTable: 'etl.douyin_shortvideo_detail_refresh_state',
    lagMinutes: 22,
    lastSyncAt: '2026-04-01 10:51',
    status: 'healthy',
    note: '当前 /dashboard/creator/short-video 复用统一短视频 ADS 表，不再依赖飞书短视频 roster。',
  },
  {
    id: 'stream_dwd_taobao_goods_sale_traffic',
    streamName: '淘宝商品流量成交 DWD 链路',
    layers: ['ODS', 'DWD'],
    source: 'ods.taobao_trade_sale_goods_raw',
    target: 'dwd.taobao_goods_sale_traffic',
    checkpointTable: 'dwd.taobao_goods_sale_traffic.updated_at',
    lagMinutes: 65,
    lastSyncAt: '2026-03-12 02:40',
    status: 'healthy',
  },
  {
    id: 'stream_report_all_trade_week_platform_metrics',
    streamName: '周报平台扩展指标链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.taobao_trade_sale_raw / ods.taobao_one_alimama_marketingscenario',
    target: 'ads.report_all_trade_week_platform_metrics',
    checkpointTable: 'etl.report_all_trade_week_platform_metrics_refresh_state',
    lagMinutes: 28,
    lastSyncAt: '2026-02-28 14:35',
    status: 'healthy',
    note: '用于天猫平台页核心指标（访客、支付转化率、UV价值、ROI）。',
  },
  {
    id: 'stream_report_douyin_trade_sale_metrics_week',
    streamName: '周报抖音经营指标链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.douyin_trade_sale_raw',
    target: 'ads.report_douyin_trade_sale_metrics_week',
    checkpointTable: 'etl.report_douyin_trade_sale_metrics_week_refresh_state',
    lagMinutes: 27,
    lastSyncAt: '2026-03-03 19:32',
    status: 'healthy',
    note: '聚合抖音店铺成交概览全指标（含支付/流量/转化/退款）周同期口径。',
  },
  {
    id: 'stream_report_douyin_trade_sale_channel_metrics_week',
    streamName: '周报抖音渠道GMV链路',
    layers: ['ODS', 'ADS'],
    source:
      'ods.douyin_trade_sale_live_raw / ods.douyin_trade_sale_shortvideo_raw / ods.douyin_trade_sale_card_raw',
    target: 'ads.report_douyin_trade_sale_channel_metrics_week',
    checkpointTable: 'etl.report_douyin_trade_sale_channel_metrics_week_refresh_state',
    lagMinutes: 29,
    lastSyncAt: '2026-03-03 16:35',
    status: 'healthy',
    note: '仅聚合直播GMV、短视频GMV、商品卡GMV，不使用总盘口径。',
  },
  {
    id: 'stream_report_douyin_trade_sale_attribution_metrics_week',
    streamName: '周报抖音归因明细链路',
    layers: ['ODS', 'ADS'],
    source:
      'ods.douyin_trade_sale_live_raw / ods.douyin_trade_sale_shortvideo_raw / ods.douyin_trade_sale_card_raw / ods.douyin_trade_sale_card_detail_raw',
    target:
      'ads.report_douyin_trade_sale_live_metrics_week / ads.report_douyin_trade_sale_shortvideo_metrics_week / ads.report_douyin_trade_sale_card_metrics_week',
    checkpointTable:
      'etl.report_douyin_trade_sale_live_metrics_week_refresh_state / etl.report_douyin_trade_sale_shortvideo_metrics_week_refresh_state / etl.report_douyin_trade_sale_card_metrics_week_refresh_state',
    lagMinutes: 30,
    lastSyncAt: '2026-03-05 18:37',
    status: 'healthy',
    note: '用于周报抖音归因明细模块，定位直播场次、短视频内容与商品卡商品/来源。',
  },
  {
    id: 'stream_report_taobao_trade_product_metrics_week',
    streamName: '周报天猫商品归因链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.taobao_trade_sale_goods_raw',
    target: 'ads.report_taobao_trade_product_metrics_week',
    checkpointTable: 'etl.report_taobao_trade_product_metrics_week_refresh_state',
    lagMinutes: 31,
    lastSyncAt: '2026-02-28 14:40',
    status: 'healthy',
    note: '用于周报天猫页商品归因分析与单品增量瀑布。',
  },
  {
    id: 'stream_report_taobao_goods_traffic_channel_metrics_week',
    streamName: '周报天猫商品流量渠道归因链路',
    layers: ['DWD', 'ADS'],
    source: 'dwd.taobao_goods_sale_traffic',
    target: 'ads.report_taobao_goods_traffic_channel_metrics_week',
    checkpointTable: 'etl.report_taobao_goods_traffic_channel_metrics_week_refresh_state',
    lagMinutes: 34,
    lastSyncAt: '2026-02-28 14:45',
    status: 'healthy',
    note: '用于周报天猫页商品流量渠道定位与渠道GMV瀑布。',
  },
  {
    id: 'stream_report_taobao_one_goods_traffic_channel_metric_week',
    streamName: '周报淘宝万相台流量漏斗链路',
    layers: ['ODS', 'ADS'],
    source: 'ods.taobao_one_alimama_goods_marketingscenario',
    target: 'ads.report_taobao_one_goods_traffic_channel_metric_week',
    checkpointTable: 'etl.report_taobao_one_goods_traffic_channel_metric_week_refresh_state',
    lagMinutes: 37,
    lastSyncAt: '2026-03-02 18:48',
    status: 'healthy',
    note: '用于周报淘宝页流量漏斗、推广指标详情与五因子量化归因。',
  },
];
